// resources/js/Pages.bak/Pages/Users/Index.svelte
<script>
    import AuthenticatedLayout, { title } from '@/Layouts/Authenticated'
    import { page } from '@inertiajs/inertia-svelte'
    import { route, checkRole, checkPermission } from '@/Utils'
    import { _ } from 'svelte-i18n'
    import { Inertia } from '@inertiajs/inertia'

    import Button from '@/Shared/Button'
    import Pagination from '@/Shared/Pagination'
    import Dialog from '@/Shared/Dialog'
    import DataTable from '@/Shared/DataTable'
    import DataTableMenu from '@/Shared/DataTableMenu'
    import { Item, Text, Separator } from '@smui/list'

    export let usuarios
    export let roles
    export let allowedToCreate

    $title = 'Usuarios'

    /**
     * Validar si el usuario autenticado es SuperAdmin
     */
    let authUser = $page.props.auth.user
    let isSuperAdmin = checkRole(authUser, [1])

    let filters = {
        roles: $page.props.filters.roles,
    }

    let dialogEliminar = false
    let allowedToDestroy = false
    let usuarioId
    function destroy() {
        if (allowedToDestroy && usuarioId) {
            Inertia.delete(route('users.destroy', usuarioId), {
                preserveScroll: true,
                onFinish: () => {
                    dialogEliminar = false
                },
            })
        }
    }
</script>

<AuthenticatedLayout>
    <DataTable class="mt-20" bind:filters showFilters={true}>
        <div slot="title">Usuarios</div>

        <div slot="filters">
            <label for="roles" class="block text-gray-700">Roles:</label>
            <select id="roles" class="mt-1 w-full form-select" bind:value={filters.roles}>
                <option value={null}>Seleccione un rol</option>
                {#each roles as role}
                    <option value={role.name}>{role.name}</option>
                {/each}
            </select>
        </div>
        <div slot="actions">
            {#if allowedToCreate}
                <Button on:click={() => Inertia.visit(route('users.online'))} variant="raised" class="ml-1">Usuarios en línea</Button>
                <Button on:click={() => Inertia.visit(route('users.create'))} variant="raised">Crear usuario</Button>
            {/if}
        </div>

        <thead slot="thead">
            <tr class="text-left font-bold">
                <th class="px-6 pt-6 pb-4 sticky top-0 z-10 bg-white shadow-xl w-full">Nombre</th>
                <th class="px-6 pt-6 pb-4 sticky top-0 z-10 bg-white shadow-xl w-full">Correo electrónico</th>
                <th class="px-6 pt-6 pb-4 sticky top-0 z-10 bg-white shadow-xl w-full">Centro de formación</th>
                <th class="px-6 pt-6 pb-4 sticky top-0 z-10 bg-white shadow-xl w-full">Rol</th>
                <th class="px-6 pt-6 pb-4 sticky top-0 z-10 bg-white shadow-xl text-center th-actions">Acciones</th>
            </tr>
        </thead>
        <tbody slot="tbody">
            {#each usuarios.data as usuario (usuario.id)}
                <tr class="hover:bg-gray-100 focus-within:bg-gray-100">
                    <td class="border-t">
                        <p class="px-6 py-4 focus:text-app-500">
                            {usuario.nombre}
                        </p>
                    </td>
                    <td class="border-t">
                        <p class="px-6 py-4">
                            {usuario.email}
                        </p>
                    </td>
                    <td class="border-t">
                        <p class="px-6 py-4">
                            {usuario.centro_formacion?.nombre}
                        </p>
                    </td>
                    <td class="border-t">
                        <ul class="px-6 py-4 list-disc">
                            {#each usuario.roles as role}
                                <li>{role.name}</li>
                            {/each}
                        </ul>
                    </td>
                    <td class="border-t td-actions">
                        <DataTableMenu class={usuarios.data.length < 3 ? 'z-50' : ''}>
                            <Item on:SMUI:action={() => Inertia.visit(route('users.edit', usuario.id))} disabled={!usuario.allowed.to_view || !usuario.allowed.to_update} class={!usuario.allowed.to_view || !usuario.allowed.to_update ? 'hidden' : ''}>
                                <Text>Ver detalles</Text>
                            </Item>

                            <Separator class={!usuario.allowed.to_destroy ? 'hidden' : ''} />
                            <Item on:SMUI:action={() => ((usuarioId = usuario.id), (dialogEliminar = true), (allowedToDestroy = usuario.allowed.to_destroy))} disabled={!usuario.allowed.to_destroy} class={!usuario.allowed.to_destroy ? 'hidden' : ''}>
                                <Text>Eliminar</Text>
                            </Item>
                        </DataTableMenu>
                    </td>
                </tr>
            {/each}

            {#if usuarios.data.length === 0}
                <tr>
                    <td class="border-t px-6 py-4" colspan="5">Sin información registrada</td>
                </tr>
            {/if}
        </tbody>
    </DataTable>
    <Pagination links={usuarios.links} />

    <Dialog bind:open={dialogEliminar}>
        <div slot="title">
            <div class="text-center">Eliminar recurso</div>
            <div class="relative bg-app-100 text-app-600 p-5 h-44 w-1/3 m-auto my-10" style="border-radius: 41% 59% 70% 30% / 32% 40% 60% 68% ;">
                <figure>
                    <img src="/images/eliminar.png" alt="" class="h-44 m-auto" />
                </figure>
            </div>
            <div class="text-center">
                ¿Está seguro (a) que desea eliminar este elemento?<br />Una vez eliminado todos sus recursos y datos se eliminarán de forma permanente.
            </div>
        </div>
        <div slot="content" />
        <div slot="actions">
            <div class="p-4">
                <Button on:click={() => (dialogEliminar = false)} variant={null}>Cancelar</Button>
                <Button variant="raised" type="button" on:click={() => destroy()}>Confirmar</Button>
            </div>
        </div>
    </Dialog>
</AuthenticatedLayout>

// resources/js/Pages/Users/Index.jsx
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout'

import ButtonMui from '@/Components/Button'
import MenuMui from '@/Components/Menu'
import PaginationMui from '@/Components/Pagination'
import SearchBar from '@/Components/SearchBar'
import TableMui from '@/Components/Table'
import TabsMui from '@/Components/TabsMui'

import AddCircleOutlineOutlinedIcon from '@mui/icons-material/AddCircleOutlineOutlined'
import MoreVertIcon from '@mui/icons-material/MoreVert'
import { Grid, MenuItem, TableCell, TableRow } from '@mui/material'

import { useState } from 'react'
import { router } from '@inertiajs/react'

import { route, checkRole } from '@/Utils'

const Index = ({ auth, usuarios, dinamizadores_sennova, subdirectores_centro, allowed_to_create }) => {
    const auth_user = auth.user
    const is_super_admin = checkRole(auth_user, [1])

    const [user_to_destroy, setUserToDestroy] = useState(null)

    const tabs = checkRole(auth_user, [1, 20]) ? [{ label: 'Usuarios' }, { label: 'Dinamizadores SENNOVA' }, { label: 'Subdirectores de centro' }] : [{ label: 'Usuarios' }]
    return (
        <AuthenticatedLayout header={<h2 className="font-semibold text-xl text-gray-800 leading-tight">Usuarios</h2>}>
            <Grid item md={12}>
                <div></div>
            </Grid>

            <TabsMui tabs={tabs}>
                <Grid item md={12}>
                    <SearchBar className="mt-20" />

                    <TableMui className="mt-20" rows={['Nombre', 'Correo electrónico', 'Centro de formación', 'Regional', 'Acciones']} sxCellThead={{ width: '320px' }}>
                        {allowed_to_create ? (
                            <TableRow onClick={() => router.visit(route('users.create'))} variant="raised" className="bg-app-100 hover:bg-app-50 hover:cursor-pointer">
                                <TableCell colSpan={5}>
                                    <ButtonMui>
                                        <AddCircleOutlineOutlinedIcon className="mr-1" /> Crear usuario
                                    </ButtonMui>
                                </TableCell>
                            </TableRow>
                        ) : null}
                        {usuarios.data.map((usuario, i) => (
                            <TableRow key={i}>
                                <TableCell>{usuario.nombre}</TableCell>
                                <TableCell>{usuario.email}</TableCell>
                                <TableCell>{usuario.centro_formacion?.nombre}</TableCell>
                                <TableCell>{usuario.centro_formacion?.regional.nombre}</TableCell>

                                <TableCell>
                                    <MenuMui text={<MoreVertIcon />}>
                                        {usuario.id !== user_to_destroy ? (
                                            <div>
                                                <MenuItem onClick={() => router.visit(route('users.edit', [usuario.id]))} disabled={!usuario?.allowed?.to_view}>
                                                    {usuario?.allowed?.to_view && !usuario?.allowed?.to_update ? 'Ver información' : 'Editar'}
                                                </MenuItem>

                                                {is_super_admin && (
                                                    <MenuItem
                                                        onClick={() => {
                                                            setUserToDestroy(usuario.id)
                                                        }}>
                                                        Eliminar
                                                    </MenuItem>
                                                )}
                                            </div>
                                        ) : (
                                            <div>
                                                <MenuItem
                                                    onClick={(e) => {
                                                        setUserToDestroy(null)
                                                    }}>
                                                    Cancelar
                                                </MenuItem>
                                                <MenuItem
                                                    sx={{ backgroundColor: 'rgba(0, 0, 0, 0.04)' }}
                                                    onClick={(e) => {
                                                        e.stopPropagation()
                                                        if (usuario.allowed.to_update) {
                                                            router.delete(route('users.destroy', [usuario.id]), {
                                                                preserveScroll: true,
                                                            })
                                                        }
                                                    }}>
                                                    Confirmar
                                                </MenuItem>
                                            </div>
                                        )}
                                    </MenuMui>
                                </TableCell>
                            </TableRow>
                        ))}
                    </TableMui>

                    <PaginationMui links={usuarios.links} className="mt-8" />
                </Grid>

                <Grid item md={12}>
                    <TableMui className="mt-20" rows={['Nombre', 'Centro de formación al que pertenece', 'Dinamizador/a del centro de formación:', 'Acciones']} sxCellThead={{ width: '320px' }}>
                        {dinamizadores_sennova.map((dinamizador_sennova, i) => (
                            <TableRow key={i}>
                                <TableCell>{dinamizador_sennova.nombre}</TableCell>
                                <TableCell>
                                    {dinamizador_sennova.centro_formacion?.nombre} - Código: {dinamizador_sennova.centro_formacion?.codigo}
                                </TableCell>
                                <TableCell>
                                    {dinamizador_sennova.dinamizador_centro_formacion ? (
                                        dinamizador_sennova.dinamizador_centro_formacion?.nombre + ' - Código: ' + dinamizador_sennova.dinamizador_centro_formacion?.codigo
                                    ) : (
                                        <span className="text-red-500 bg-red-100 p-2 block">Tiene rol Dinamizador/a pero no tiene ningún Centro relacionado</span>
                                    )}
                                </TableCell>

                                <TableCell>
                                    <MenuMui text={<MoreVertIcon />}>
                                        {dinamizador_sennova.id !== user_to_destroy ? (
                                            <div>
                                                <MenuItem onClick={() => router.visit(route('users.edit', [dinamizador_sennova.id]))} disabled={!checkRole(auth_user, [1, 20])}>
                                                    Editar
                                                </MenuItem>

                                                <MenuItem
                                                    onClick={() => {
                                                        setUserToDestroy(dinamizador_sennova.id)
                                                    }}
                                                    disabled={!checkRole(auth_user, [1, 20, 18, 19, 5, 17])}>
                                                    Eliminar
                                                </MenuItem>
                                            </div>
                                        ) : (
                                            <div>
                                                <MenuItem
                                                    onClick={(e) => {
                                                        setUserToDestroy(null)
                                                    }}>
                                                    Cancelar
                                                </MenuItem>
                                                <MenuItem
                                                    sx={{ backgroundColor: 'rgba(0, 0, 0, 0.04)' }}
                                                    onClick={(e) => {
                                                        e.stopPropagation()
                                                        if (checkRole(auth_user, [1, 20, 18, 19, 5, 17])) {
                                                            router.delete(route('users.destroy', [dinamizador_sennova.id]), {
                                                                preserveScroll: true,
                                                            })
                                                        }
                                                    }}>
                                                    Confirmar
                                                </MenuItem>
                                            </div>
                                        )}
                                    </MenuMui>
                                </TableCell>
                            </TableRow>
                        ))}
                    </TableMui>
                </Grid>

                <Grid item md={12}>
                    <TableMui className="mt-20" rows={['Nombre', 'Centro de formación al que pertenece', 'Subdirector/a del centro de formación:', 'Acciones']} sxCellThead={{ width: '320px' }}>
                        {subdirectores_centro.map((subdirector_centro, i) => (
                            <TableRow key={i}>
                                <TableCell>{subdirector_centro.nombre}</TableCell>
                                <TableCell>
                                    {subdirector_centro.centro_formacion?.nombre} - Código: {subdirector_centro.centro_formacion?.codigo}
                                </TableCell>
                                <TableCell>
                                    {subdirector_centro.subdirector_centro_formacion ? (
                                        subdirector_centro.subdirector_centro_formacion?.nombre + ' - Código: ' + subdirector_centro.subdirector_centro_formacion?.codigo
                                    ) : (
                                        <span className="text-red-500 bg-red-100 p-2 block">Tiene rol Subdirector/a de Centro de Formación pero no tiene ningún Centro relacionado</span>
                                    )}
                                </TableCell>

                                <TableCell>
                                    <MenuMui text={<MoreVertIcon />}>
                                        {subdirector_centro.id !== user_to_destroy ? (
                                            <div>
                                                <MenuItem onClick={() => router.visit(route('users.edit', [subdirector_centro.id]))} disabled={!checkRole(auth_user, [1, 20])}>
                                                    Editar
                                                </MenuItem>

                                                <MenuItem
                                                    onClick={() => {
                                                        setUserToDestroy(subdirector_centro.id)
                                                    }}
                                                    disabled={!checkRole(auth_user, [1, 20, 18, 19, 5, 17])}>
                                                    Eliminar
                                                </MenuItem>
                                            </div>
                                        ) : (
                                            <div>
                                                <MenuItem
                                                    onClick={(e) => {
                                                        setUserToDestroy(null)
                                                    }}>
                                                    Cancelar
                                                </MenuItem>
                                                <MenuItem
                                                    sx={{ backgroundColor: 'rgba(0, 0, 0, 0.04)' }}
                                                    onClick={(e) => {
                                                        e.stopPropagation()
                                                        if (checkRole(auth_user, [1, 20, 18, 19, 5, 17])) {
                                                            router.delete(route('users.destroy', [subdirector_centro.id]), {
                                                                preserveScroll: true,
                                                            })
                                                        }
                                                    }}>
                                                    Confirmar
                                                </MenuItem>
                                            </div>
                                        )}
                                    </MenuMui>
                                </TableCell>
                            </TableRow>
                        ))}
                    </TableMui>
                </Grid>
            </TabsMui>
        </AuthenticatedLayout>
    )
}

export default Index
