// resources/js/Pages/Dashboard.jsx
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout'
import { route, checkRole, checkPermission } from '@/Utils'
import { Link } from '@inertiajs/react'

export default function Dashboard({ auth }) {
    const auth_user = auth.user
    const is_super_admin = checkRole(auth_user, [1])

    return (
        <AuthenticatedLayout user={auth.user} header={<h2 className="font-semibold text-xl text-gray-800 leading-tight">Dashboard</h2>}>
            <div className="grid grid-cols-3 gap-4 mb-10">
                <div className="flex items-center justify-between rounded-xl px-10 py-20 text-app-800 bg-app-300/50 col-span-2">
                    <div className="max-w-2xl">
                        <h1 className="text-2xl font-bold">
                            ¡Bienvenido(a) <span className="capitalize">{auth.user.nombre}</span>! 👋🏻
                        </h1>

                        <p className="my-8">Formule proyectos de I+D+i, Tecnoacademia-Tecnoparque, Servicios Tecnológicos y/o Cultura de la innovación.</p>
                    </div>
                    <div>
                        <figure>
                            <img src={'/images/dashboard.png'} alt="" />
                        </figure>
                    </div>
                </div>
            </div>
            <div className="grid grid-cols-3 gap-10">
                <Link
                    className="bg-white overflow-hidden rounded-lg px-6 py-2 hover:bg-app-800 hover:text-white h-[200px] shadow-md flex justify-around items-center flex-col"
                    href={route('convocatorias.index')}>
                    Convocatorias
                </Link>

                {is_super_admin || checkRole(auth_user, [4]) || checkPermission(auth_user, [8, 17]) ? (
                    <Link
                        className="bg-white overflow-hidden rounded-lg px-6 py-2 hover:bg-app-800 hover:text-white h-[200px] shadow-md flex justify-around items-center flex-col text-center"
                        href={route('nuevos-proyectos-ta-tp')}>
                        Nuevos proyectos Tecnoacademia - Tecnoparque
                    </Link>
                ) : null}

                {is_super_admin || checkRole(auth_user, [4, 5, 17, 18, 19, 21]) ? (
                    <Link
                        className="bg-white overflow-hidden rounded-lg px-6 py-2 hover:bg-app-800 hover:text-white h-[200px] shadow-md flex justify-around items-center flex-col"
                        href={route('users.index')}>
                        Usuarios
                    </Link>
                ) : null}
            </div>

            {/* <Dialog bind:open={dialogOpen} id="informacion">
                <div slot="title" className="flex items-center flex-col mb-10">Importante</div>
                <div slot="content">
                    <small>Junio 8</small>

                    <hr className="mt-10 mb-10" />
                    <div>
                        <p>El CENSO SENNOVA 2023 está habilitado. Por favor haga clic en <strong>Ir al CENSO SENNOVA 2023</strong> para diligenciarlo.</p>
                    </div>
                </div>
                <div slot="actions">
                    <div className="p-4 flex">
                        {#if auth_user.informacion_completa}
                            <Button variant="outlined" on:click={() => (dialogOpen = false)}>Ya he completado el CENSO</Button>
                        }
                        <Link className="ml-2 overflow-hidden shadow-sm rounded px-6 py-2 bg-app-500 text-white flex justify-around items-center flex-col text-center" href={route('users.perfil')}>Ir al CENSO SENNOVA 2023</Link>
                    </div>
                </div>
            </Dialog> */}
        </AuthenticatedLayout>
    )
}

// resources/js/Pages/Convocatorias/Dashboard.svelte
<script>
    import AuthenticatedLayout, { title } from '@/Layouts/Authenticated'
    import { inertia, page } from '@inertiajs/inertia-svelte'
    import { route, checkRole, checkPermission } from '@/Utils'
    import { _ } from 'svelte-i18n'

    export let convocatoria

    let authUser = $page.props.auth.user
    let isSuperAdmin = checkRole(authUser, [1])

    $title = 'Convocatorias - Dashboard'
</script>

<AuthenticatedLayout>
    <div class="py-12">
        {#if isSuperAdmin || checkRole(authUser, [11]) || checkPermission(authUser, [1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 17, 18, 19, 14, 15, 16, 20, 21])}
            <h1 class="text-4xl text-center">
                A continuación, se listan las líneas programáticas de la vigencia {convocatoria.year} en las que puede formular proyectos.
            </h1>
            <div class="flex justify-around flex-wrap mt-24 gap-4 mb-12">
                <div class="w-80 h-96{isSuperAdmin || checkPermission(authUser, [1, 3, 4, 14, 11, 18]) || checkRole(authUser, [11, 5]) ? '' : ' hidden'}">
                    {#if isSuperAdmin || checkPermission(authUser, [1, 3, 4, 14])}
                        <a use:inertia href={route('convocatorias.idi.index', convocatoria.id)} class="bg-white overflow-hidden z-[2] relative text-center shadow-sm sm:rounded-lg px-6 py-2 hover:bg-app-500 hover:text-white flex justify-around items-center flex-col m-auto h-96">
                            <figure>
                                <img src={  '/images/idi.png'} alt="Línea programática - I+D+i" class="bg-white h-44 w-44 object-contain rounded-full" />
                            </figure>
                            Formular proyectos de I+D+i
                        </a>
                    {:else}
                        <div class="bg-white opacity-25 overflow-hidden z-[2] relative text-center shadow-sm sm:rounded-lg px-6 py-2 hover:bg-app-500 hover:text-white flex justify-around items-center flex-col m-auto h-96">
                            <figure>
                                <img src={  '/images/idi.png'} alt="Línea programática - I+D+i" class="bg-white h-44 w-44 object-contain rounded-full" />
                            </figure>
                            Formular proyectos de I+D+i
                        </div>
                    {/if}
                    {#if isSuperAdmin || checkRole(authUser, [11, 18])}
                        <a use:inertia href={route('convocatorias.idi-evaluaciones.index', convocatoria.id)} class="bg-app-500 px-6 py-4 shadow-sm sm:rounded-lg transition duration-300 text-center text-white hover:bg-white hover:text-black z-[1] relative block w-80 mt-2"> Evaluar proyectos de I+D+i </a>
                    {/if}
                </div>
                <div class="w-80 h-96{isSuperAdmin || (checkPermission(authUser, [8, 9, 10, 15]) && convocatoria.tipo_convocatoria == 1) || (checkPermission(authUser, [8, 9, 10, 15]) && convocatoria.tipo_convocatoria == 3) || checkRole(authUser, [11, 5]) ? '' : ' hidden'}">
                    {#if isSuperAdmin || (checkPermission(authUser, [8, 9, 10, 15]) && convocatoria.tipo_convocatoria == 1) || (checkPermission(authUser, [8, 9, 10, 15]) && convocatoria.tipo_convocatoria == 3)}
                        <a use:inertia href={route('convocatorias.ta.index', convocatoria.id)} class="bg-white overflow-hidden z-[2] relative text-center shadow-sm sm:rounded-lg px-6 py-2 hover:bg-app-500 hover:text-white flex justify-around items-center flex-col m-auto h-96">
                            <figure>
                                <img src={  '/images/ta.png'} alt="Línea programática - Tecnoacademia" class="bg-white h-44 w-44 object-contain rounded-full" />
                            </figure>
                            Formular proyectos de Tecnoacademia
                        </a>
                    {:else}
                        <div class="bg-white opacity-25 overflow-hidden z-[2] relative text-center shadow-sm sm:rounded-lg px-6 py-2 hover:bg-app-500 hover:text-white flex justify-around items-center flex-col m-auto h-96">
                            <figure>
                                <img src={  '/images/ta.png'} alt="Línea programática - Tecnoacademia" class="bg-white h-44 w-44 object-contain rounded-full" />
                            </figure>
                            Formular proyectos de Tecnoacademia
                        </div>
                    {/if}
                    {#if isSuperAdmin || checkRole(authUser, [11, 5])}
                        <a use:inertia href={route('convocatorias.ta-evaluaciones.index', convocatoria.id)} class="bg-app-500 px-6 py-4 shadow-sm sm:rounded-lg transition duration-300 text-center text-white hover:bg-white hover:text-black z-[1] relative block w-80 mt-2"> Evaluar proyectos de Tecnoacademia </a>
                    {/if}
                </div>

                <div class="w-80 h-96{isSuperAdmin || (checkPermission(authUser, [17, 18, 19, 20]) && convocatoria.tipo_convocatoria == 1) || (checkPermission(authUser, [17, 18, 19, 20]) && convocatoria.tipo_convocatoria == 3) || checkRole(authUser, [11, 17]) ? '' : ' hidden'}">
                    {#if isSuperAdmin || (checkPermission(authUser, [17, 18, 19, 20]) && convocatoria.tipo_convocatoria == 1) || (checkPermission(authUser, [17, 18, 19, 20]) && convocatoria.tipo_convocatoria == 3)}
                        <a use:inertia href={route('convocatorias.tp.index', convocatoria.id)} class="bg-white overflow-hidden z-[2] relative text-center shadow-sm sm:rounded-lg px-6 py-2 hover:bg-app-500 hover:text-white flex justify-around items-center flex-col m-auto h-96">
                            <figure>
                                <img src={  '/images/tp.png'} alt="Línea programática - Tecnoparque" class="bg-white h-44 w-44 object-contain rounded-full" />
                            </figure>
                            Formular proyectos de Tecnoparque
                        </a>
                    {:else}
                        <div class="bg-white opacity-25 overflow-hidden z-[2] relative text-center shadow-sm sm:rounded-lg px-6 py-2 hover:bg-app-500 hover:text-white flex justify-around items-center flex-col m-auto h-96">
                            <figure>
                                <img src={  '/images/tp.png'} alt="Línea programática - Tecnoparque" class="bg-white h-44 w-44 object-contain rounded-full" />
                            </figure>
                            Formular proyectos de Tecnoparque
                        </div>
                    {/if}
                    {#if isSuperAdmin || checkRole(authUser, [11, 17])}
                        <a use:inertia href={route('convocatorias.tp-evaluaciones.index', convocatoria.id)} class="bg-app-500 px-6 py-4 shadow-sm sm:rounded-lg transition duration-300 text-center text-white hover:bg-white hover:text-black z-[1] relative block w-80 mt-2"> Evaluar proyectos de Tecnoparque </a>
                    {/if}
                </div>

                <div class="w-80 h-96 mt-16{isSuperAdmin || (checkPermission(authUser, [5, 6, 7, 16]) && convocatoria.tipo_convocatoria == 1) || (checkPermission(authUser, [5, 6, 7, 16]) && convocatoria.tipo_convocatoria == 3) || checkRole(authUser, [11, 19]) ? '' : ' hidden'}">
                    {#if isSuperAdmin || (checkPermission(authUser, [5, 6, 7, 16]) && convocatoria.tipo_convocatoria == 1) || (checkPermission(authUser, [5, 6, 7, 16]) && convocatoria.tipo_convocatoria == 3)}
                        <a use:inertia href={route('convocatorias.servicios-tecnologicos.index', convocatoria.id)} class="bg-white overflow-hidden z-[2] relative text-center shadow-sm sm:rounded-lg px-6 py-2 hover:bg-app-500 hover:text-white flex justify-around items-center flex-col m-auto h-96">
                            <figure>
                                <img src={  '/images/st.png'} alt="Línea programática - Servicios tecnológicos" class="bg-white h-44 w-44 object-contain rounded-full" />
                            </figure>
                            Formular proyectos de Servicios Tecnológicos
                        </a>
                    {:else}
                        <div class="bg-white opacity-25 overflow-hidden z-[2] relative text-center shadow-sm sm:rounded-lg px-6 py-2 hover:bg-app-500 hover:text-white flex justify-around items-center flex-col m-auto h-96">
                            <figure>
                                <img src={  '/images/st.png'} alt="Línea programática - Servicios tecnológicos" class="bg-white h-44 w-44 object-contain rounded-full" />
                            </figure>
                            Formular proyectos de Servicios Tecnológicos
                        </div>
                    {/if}
                    {#if isSuperAdmin || checkRole(authUser, [11, 19])}
                        <a use:inertia href={route('convocatorias.servicios-tecnologicos-evaluaciones.index', convocatoria.id)} class="bg-app-500 px-6 py-4 shadow-sm sm:rounded-lg transition duration-300 text-center text-white hover:bg-white hover:text-black z-[1] relative block mt-2"> Evaluar proyectos Servicios Tecnológicos </a>
                    {/if}
                </div>

                <div class="w-80 h-96 mt-16{isSuperAdmin || (checkPermission(authUser, [11, 12, 13, 21]) && convocatoria.tipo_convocatoria == 1) || (checkPermission(authUser, [11, 12, 13, 21]) && convocatoria.tipo_convocatoria == 3) || checkRole(authUser, [11, 20]) ? '' : ' hidden'}">
                    {#if isSuperAdmin || (checkPermission(authUser, [11, 12, 13, 21]) && convocatoria.tipo_convocatoria == 1) || (checkPermission(authUser, [11, 12, 13, 21]) && convocatoria.tipo_convocatoria == 3)}
                        <a use:inertia href={route('convocatorias.cultura-innovacion.index', convocatoria.id)} class="bg-white overflow-hidden z-[2] relative text-center shadow-sm sm:rounded-lg px-6 py-2 hover:bg-app-500 hover:text-white flex justify-around items-center flex-col m-auto h-96">
                            <figure>
                                <img src={  '/images/cultura-innovacion.png'} alt="Línea programática - Servicios tecnológicos" class="bg-white h-44 w-44 object-contain rounded-full" />
                            </figure>
                            Formular proyectos de Apropiación de la cultura de la innovación
                        </a>
                    {:else}
                        <div class="bg-white opacity-25 overflow-hidden z-[2] relative text-center shadow-sm sm:rounded-lg px-6 py-2 hover:bg-app-500 hover:text-white flex justify-around items-center flex-col m-auto h-96">
                            <figure>
                                <img src={  '/images/cultura-innovacion.png'} alt="Línea programática - Servicios tecnológicos" class="bg-white h-44 w-44 object-contain rounded-full" />
                            </figure>
                            Formular proyectos de Apropiación de la cultura de la innovación
                        </div>
                    {/if}
                    {#if isSuperAdmin || checkRole(authUser, [11, 20])}
                        <a use:inertia href={route('convocatorias.cultura-innovacion-evaluaciones.index', convocatoria.id)} class="bg-app-500 px-6 py-4 shadow-sm sm:rounded-lg transition duration-150 text-center text-white hover:bg-white hover:text-black z-[1] relative block w-80 mt-2"> Evaluar proyectos de apropiación proyectos de la cultura de la innovación </a>
                    {/if}
                </div>
            </div>
        {/if}
    </div>
</AuthenticatedLayout>
