// resources/js/Pages.bak/Pages/Convocatorias/Proyectos/AnalisisRiesgo/Edit.svelte
<script>
    import AuthenticatedLayout, { title } from '@/Layouts/Authenticated'
    import { inertia, useForm, page } from '@inertiajs/inertia-svelte'
    import { route, checkRole, checkPermission } from '@/Utils'
    import { _ } from 'svelte-i18n'

    import Form from './Form'

    export let errors
    export let convocatoria
    export let proyecto
    export let analisisRiesgo
    export let nivelesRiesgo
    export let tiposRiesgo
    export let probabilidadesRiesgo
    export let impactosRiesgo

    $: $title = analisisRiesgo ? 'Análisis de riesgos - ' + analisisRiesgo.nivel : null

    /**
     * Validar si el usuario autenticado es SuperAdmin
     */
    let authUser = $page.props.auth.user
    let isSuperAdmin = checkRole(authUser, [1])

    let form = useForm({
        nivel: analisisRiesgo.nivel,
        tipo: analisisRiesgo.tipo,
        descripcion: analisisRiesgo.descripcion,
        impacto: analisisRiesgo.impacto,
        probabilidad: analisisRiesgo.probabilidad,
        efectos: analisisRiesgo.efectos,
        medidas_mitigacion: analisisRiesgo.medidas_mitigacion,
    })

    function submit() {
        if (proyecto.allowed.to_update) {
            $form.put(route('convocatorias.proyectos.analisis-riesgos.update', [convocatoria.id, proyecto.id, analisisRiesgo.id]), {
                preserveScroll: true,
            })
        }
    }
</script>

<AuthenticatedLayout>
    <header class="pt-[8rem]" slot="header">
        <div class="flex items-center justify-between lg:px-8 max-w-7xl mx-auto px-4 py-6 sm:px-6">
            <div>
                <h1 class="overflow-ellipsis overflow-hidden w-breadcrumb-ellipsis whitespace-nowrap">
                    <a use:inertia href={route('convocatorias.proyectos.analisis-riesgos.index', [convocatoria.id, proyecto.id])} class="text-app-400 hover:text-app-600">Análisis de riesgos</a>
                    <span class="text-app-400 font-medium">/</span>
                    {analisisRiesgo.tipo}
                </h1>
            </div>
        </div>
    </header>

    <div class="grid grid-cols-3 gap-4">
        <div class="sticky top-0">
            <h1 class="font-black text-4xl uppercase">Editar análisis de riesgo</h1>
        </div>

        <div class="bg-white rounded shadow col-span-2">
            <Form {errors} {proyecto} {analisisRiesgo} {nivelesRiesgo} {tiposRiesgo} {probabilidadesRiesgo} {impactosRiesgo} {form} {submit} />
        </div>
    </div>
</AuthenticatedLayout>

// resources/js/Pages/Convocatorias/Edit.jsx
import { useForm } from '@inertiajs/react';
import { route, checkRole } from '@/Utils';

import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import Label from '@/Components/Label';
// import InputError from '@/Components/InputError';
import PrimaryButton from '@/Components/PrimaryButton';
import Textarea from '@/Components/Textarea';
import Switch from '@/Components/Switch';
import Autocomplete from '@/Components/Autocomplete';
import MultipleSelect from '@/Components/MultipleSelect';

const EditConvocatoria = ({ auth, errors, convocatoria, lineasProgramaticas, lineasProgramaticasActivasRelacionadas, fases }) => {

  // Validar si el usuario autenticado es SuperAdmin
  const authUser = auth.user;
  const isSuperAdmin = checkRole(authUser, [1]);

    const submitFase = (e) => {
        e.preventDefault()

        postFase(route('convocatorias.update-fase', convocatoria.id))
    };

const { data: dataFase, setData: setDataFase, post: postFase, processing: processingFase, errors: errorsFase, reset: resetFase } = useForm({
    fase: convocatoria.fase,
    fecha_finalizacion_fase: convocatoria.fecha_finalizacion_fase,
    hora_finalizacion_fase: convocatoria.hora_finalizacion_fase,
  });

  const { data: dataConvocatoria, setData: setDataConvocatoria, put: putConvocatoria, processing: processingConvocatoria, errors: errorsConvocatoria, reset: resetConvocatoria } = useForm({
    descripcion: convocatoria.descripcion,
    esta_activa: convocatoria.esta_activa,
    visible: convocatoria.visible,
    mostrar_recomendaciones: convocatoria.mostrar_recomendaciones,
    lineas_programaticas_activas: lineasProgramaticasActivasRelacionadas.length > 0 ? lineasProgramaticasActivasRelacionadas : null,
  });

  const submitInfo = (e) => {
    e.preventDefault()

    if (isSuperAdmin) {
      putConvocatoria(route('convocatorias.update', convocatoria.id), {
        preserveScroll: true,
      });
    }
  };

  return (
    <AuthenticatedLayout
        user={auth.user}
        header={<h2 className="font-semibold text-xl text-gray-800 leading-tight">Lista de convocatorias</h2>}
    >
      <header className="pt-[8rem]" slot="header">
        <div className="flex items-center justify-between lg:px-8  px-4 py-6">
          <div>
            <h1 className="overflow-ellipsis overflow-hidden w-breadcrumb-ellipsis whitespace-nowrap">
              <a href={route('convocatorias.index')} className="text-app-400 hover:text-app-600">Convocatorias</a>
              <span className="text-app-400 font-medium">/</span>
              <a href={route('convocatorias.lineas-programaticas.index', convocatoria.id)} className="text-app-400 hover:text-app-600">
                {convocatoria.descripcion}
              </a>
            </h1>
          </div>
        </div>
      </header>

      <div className="grid grid-cols-3">
        <div>
          <h1 className="font-black text-4xl uppercase">Fase</h1>
        </div>
        <div className="col-span-2">
          {convocatoria.tipo_convocatoria == 1 || convocatoria.tipo_convocatoria == 3 ? (
            <form onSubmit={submitFase} className="rounded shadow">
              <fieldset className="p-8" disabled={isSuperAdmin ? undefined : true}>
                <div className="grid grid-cols-2">
                  <div>
                    <Label required className="mb-4" labelFor="fase" value="Fase" />
                  </div>
                  <div>
                    <Autocomplete id="fase" items={fases} value={dataFase.fase} onChange={(e) => setDataFase('fase', e.target.value)} error={errors.fase} autoComplete={false} placeholder="Seleccione una fase" required />
                  </div>

                  {dataFase.fase?.label && (
                    <>
                      <div>
                        <Label required labelFor="fecha_finalizacion_fase" value={`Fecha de finalización de la fase: ${dataFase.fase.label.toLowerCase()}`} />
                      </div>
                      <div>
                        <input id="fecha_finalizacion_fase" type="date" className="mt-1 p-2" value={dataFase.fecha_finalizacion_fase} onChange={(e) => setDataFase('fecha_finalizacion_fase', e.target.value)} required />
                      </div>
                    </>
                  )}

                  <div>
                    <Label required labelFor="hora_finalizacion_fase" value="Hora límite" />
                  </div>
                  <div>
                    <input id="hora_finalizacion_fase" type="time" step="1" className="mt-1 p-2 border rounded border-gray-300" value={dataFase.hora_finalizacion_fase} onChange={(e) => setDataFase('hora_finalizacion_fase', e.target.value)} required />
                  </div>
                </div>

                <p className="mt-10">
                  {dataFase.fase?.value === 1 && (
                    <>
                      <strong>Tenga en cuenta:</strong> La fase de {dataFase.fase.label.toLowerCase()} permitirá a los formuladores crear, modificar y eliminar proyectos.
                    </>
                  )}
                  {dataFase.fase?.value === 2 && (
                    <>
                      <strong>Tenga en cuenta:</strong> La fase de {dataFase.fase.label.toLowerCase()} bloqueará a los formuladores las acciones de crear, modificar y eliminar proyectos.
                    </>
                  )}
                  {dataFase.fase?.value === 3 && (
                    <>
                      <strong>Tenga en cuenta:</strong> La fase de {dataFase.fase.label.toLowerCase()} permitirá a los formuladores modificar aquellos proyectos que pueden ser subsanados y a los evaluadores se le bloqueará la acción de modificar las evaluaciones.
                    </>
                  )}
                  {dataFase.fase?.value === 4 && (
                    <>
                      <strong>Tenga en cuenta:</strong> La fase de {dataFase.fase.label.toLowerCase()} bloqueará a los formuladores la acción de modificar aquellos proyectos que pasaron a etapa de subsanación y a los evaluadores se le habilitarán aquellas evaluaciones de proyectos subsanados.
                    </>
                  )}
                  {dataFase.fase?.value === 5 && (
                    <>
                      <strong>Tenga en cuenta:</strong> La fase de {dataFase.fase.label.toLowerCase()} bloqueará a los formuladores la modificación de proyectos y a los evaluadores la modificación de las evaluaciones.
                    </>
                  )}
                </p>
              </fieldset>
              <div className="flex items-center justify-between mt-14 px-8 py-4">
                {isSuperAdmin && (
                  <PrimaryButton className="ml-auto" type="submit" disabled={processingFase}>
                    Editar fase
                  </PrimaryButton>
                )}
              </div>
            </form>
          ) : null}
        </div>
        </div>

        <div className="grid grid-cols-3 mt-10">
            <div>
                <h1 className="font-black text-4xl uppercase">Información de la convocatoria</h1>
            </div>
            <div className="col-span-2">
                <form onSubmit={submitInfo} className="rounded shadow">
                    <fieldset className="p-8" disabled={isSuperAdmin ? undefined : true}>
                    <div className="mt-8">
                        <Textarea label="Descripción" maxlength="40000" id="descripcion" error={errors.descripcion} value={dataConvocatoria.descripcion} onChange={(e) => setDataConvocatoria('descripcion', e.target.value)} required />
                    </div>

                    <div className="mt-10 mb-20">
                        <Label required labelFor="esta_activa" value="¿Desea activar esta convocatoria? (Si la opción está habilitada permite a los usuarios formular proyectos. Tenga en cuenta que solo puede activar una convocatoria por tipo --Proyectos de convocatoria - Proyectos de ejecicio DEMO)" className="inline-block mb-4" />
                        <br />
                        <Switch checked={dataConvocatoria.esta_activa} onChange={(e) => setDataConvocatoria('esta_activa', e.target.checked)} />
                    </div>

                    <div>
                        <div className="mt-10 mb-20">
                        <Label required labelFor="lineas_programaticas_activas" className="mb-4" value="Seleccione las líneas programáticas las cuales quiere activar" />
                        <MultipleSelect id="lineas_programaticas_activas" selectedValues={dataConvocatoria.lineas_programaticas_activas} items={lineasProgramaticas} error={errors.lineas_programaticas_activas} placeholder="Seleccione las líneas programáticas" required />
                        </div>
                    </div>

                    <div className="mt-10 mb-20">
                        <Label required labelFor="visible" value="Defina la visibilidad de la convocatoria. (Si la opción está habilitada permite a los usuarios visualizar la convocatoria)" className="inline-block mb-4" />
                        <br />
                        <Switch checked={dataConvocatoria.visible} onChange={(e) => setDataConvocatoria('visible', e.target.checked)} onMessage="Visible" offMessage="Oculta" />
                    </div>

                    {(convocatoria.tipo_convocatoria == 1 || convocatoria.tipo_convocatoria == 3) && (
                        <div className="mt-4 mb-20">
                        <Label required labelFor="mostrar_recomendaciones" value="¿Desea que el formulador visualice las recomendaciones hechas por los evaluadores?" className="inline-block mb-4" />
                        <br />
                        <Switch checked={dataConvocatoria.mostrar_recomendaciones} onChange={(e) => setDataConvocatoria('mostrar_recomendaciones', e.target.checked)} />
                        </div>
                    )}
                    </fieldset>
                    <div className="flex items-center justify-between mt-14 px-8 py-4">
                    {isSuperAdmin && (
                        <PrimaryButton type="submit" disabled={processingConvocatoria}>
                        Editar convocatoria
                        </PrimaryButton>
                    )}
                    </div>
                </form>
            </div>
      </div>
    </AuthenticatedLayout>
  );
};

export default EditConvocatoria;
