// resources/js/Shared/Label.svelte
<script>
    export let labelFor
    export let value
    export let required

    $: props = {
        ...$$restProps,
        class: `block text-sm text-gray-700 ${$$restProps.class || ''}`,
    }
</script>

{#if value}
    <label {...props} for={labelFor}>
        {@html value}
        {!required ? '(Opcional)' : ''}
        {#if required}
            <small>*</small>
        {/if}
    </label>
{/if}

// resources/js/Components/Label.jsx
const Label = ({ labelFor, value, required, ...props }) => {
   if (value) {
    return (
      <label htmlFor={labelFor} className={`block text-sm text-gray-700 ${props.className || ''}`} {...props}>
        {value}
        {!required ? '(Opcional)' : <small> *</small>}
      </label>
    );
  }

  return null;
};

export default Label;
