// resources/js/Components/Tags.jsx
import Tagify from '@yaireo/tagify'

import '@yaireo/tagify/dist/tagify.css'

import { useEffect, useRef } from 'react'
import { FormHelperText } from '@mui/material'

const Tags = ({ error, placeholder, whitelist, tags, value = '', id, enforceWhitelist = true, ...props }) => {
    const inputElm = useRef(null)
    const tagify = useRef(null)

    useEffect(() => {
        inputElm.current = document.getElementById(id)

        if (inputElm.current) {
            tagify.current = new Tagify(inputElm.current, {
                enforceWhitelist: enforceWhitelist,
                whitelist: inputElm.current.value.trim().split(/\s*,\s*/),
            })

            tagify.current.on('add', onAddTag).on('remove', onRemoveTag).on('input', onInput).on('edit', onTagEdit).on('dropdown:hide dropdown:show')
        }

        return () => {
            if (tagify.current) {
                tagify.current.destroy()
            }
        }
    }, [id, enforceWhitelist, whitelist, tags])

    const mockAjax = (duration) => {
        let timeout
        return new Promise((resolve, reject) => {
            timeout = setTimeout(resolve, duration || 700, whitelist)
        })
    }

    const onAddTag = (e) => {
        tags = inputElm.current.value
    }

    const onRemoveTag = (e) => {
        tags = inputElm.current.value
    }

    const onTagEdit = (e) => {
        tags = inputElm.current.value
    }

    const onInput = (e) => {
        tagify.current.settings.whitelist.length = 0
        tagify.current.loading(true).dropdown.hide.call(tagify.current)

        mockAjax().then((result) => {
            if (result !== undefined) {
                tagify.current.settings.whitelist.push(...result, ...tagify.current.value)
            }

            tagify.current.loading(false).dropdown.show.call(tagify.current, e.detail.value)
        })
    }

    if (value === null) {
        value = ''
    }

    return (
        <>
            <input id={id} name="tags" {...props} placeholder={placeholder} value={value} {...props} className={`!p-2 rounded ${props.className}`} />
            {error && (
                <FormHelperText id={`component-error-${id}`} className="!text-red-600">
                    {error}
                </FormHelperText>
            )}
        </>
    )
}

export default Tags

// resources/js/Shared/Tags.svelte
<script>
    import Tagify from '@yaireo/tagify'

    import '@yaireo/tagify/dist/tagify.css'
    import InputError from '@/Shared/InputError'
    import { onMount } from 'svelte'

    export let error
    export let placeholder
    export let whitelist
    export let tags
    export let id
    export let enforceWhitelist = true

    let inputElm, tagify

    let selectedValues = null

    if (tags) {
        selectedValues = JSON.parse(tags)
            .map(function (item) {
                return item.value
            })
            .join(',')
    }

    onMount(() => {
        inputElm = document.getElementById(id)

        // initialize Tagify on the above input node reference
        if (inputElm) {
            tagify = new Tagify(inputElm, {
                enforceWhitelist: enforceWhitelist,

                // make an array from the initial input value
                whitelist: inputElm.value.trim().split(/\s*,\s*/),
            })

            // Chainable event listeners
            tagify.on('add', onAddTag).on('remove', onRemoveTag).on('input', onInput).on('edit', onTagEdit).on('dropdown:hide dropdown:show')
        }
    })

    var mockAjax = (function mockAjax() {
        var timeout
        return function (duration) {
            clearTimeout(timeout) // abort last request
            return new Promise(function (resolve, reject) {
                timeout = setTimeout(resolve, duration || 700, whitelist)
            })
        }
    })()

    // tag added callback
    function onAddTag(e) {
        tags = inputElm.value
    }

    // tag remvoed callback
    function onRemoveTag(e) {
        tags = inputElm.value
    }

    function onTagEdit(e) {
        tags = inputElm.value
    }

    // on character(s) added/removed (user is typing/deleting)
    function onInput(e) {
        // console.log('onInput: ', e.detail)
        tagify.settings.whitelist.length = 0 // reset current whitelist
        tagify.loading(true).dropdown.hide.call(tagify) // show the loader animation

        // get new whitelist from a delayed mocked request (Promise)
        mockAjax().then(function (result) {
            // replace tagify "whitelist" array values with new values
            // and add back the ones already choses as Tags
            if (result != undefined) {
                tagify.settings.whitelist.push(...result, ...tagify.value)
            }

            // render the suggestions dropdown.
            tagify.loading(false).dropdown.show.call(tagify, e.detail.value)
        })
    }

    $: props = {
        ...$$restProps,
        class: `tagify-input bg-white w-full border-gray-300 rounded-md shadow-sm focus:ring focus:ring-opacity-50 focus:border-app-200 focus:ring-app-200 ${$$restProps.class || ''}`,
    }
</script>

<input {id} name="tags" {...props} {placeholder} value={selectedValues} />
<InputError message={error} />

<style>
    :global(.tagify__input::before) {
        line-height: initial;
    }
</style>
