// resources/js/Pages/Convocatorias/Proyectos/Indicadores/Index.svelte
<script>
    import AuthenticatedLayout, { title } from '@/Layouts/Authenticated'
    import { useForm, page } from '@inertiajs/inertia-svelte'
    import { _ } from 'svelte-i18n'
    import { Inertia } from '@inertiajs/inertia'

    import Label from '@/Shared/Label'
    import LoadingButton from '@/Shared/LoadingButton'
    import Stepper from '@/Shared/Stepper'
    import Textarea from '@/Shared/Textarea'

    export let convocatoria
    export let idi
    export let errors

    let form = useForm({
        productividad_beneficiaros: idi.productividad_beneficiaros,
        generacion_empleo_beneficiarios: idi.generacion_empleo_beneficiarios,
        creacion_nuevos_desarrollos: idi.creacion_nuevos_desarrollos,
        generacion_conocimientos_beneficiarios: idi.generacion_conocimientos_beneficiarios,
        generacion_valor_beneficiarios: idi.generacion_valor_beneficiarios,
        fortalecimiento_programas_formacion: idi.fortalecimiento_programas_formacion,
        transferencia_tecnologias: idi.transferencia_tecnologias,
        calidad_formacion: idi.calidad_formacion,
        impacto_ambiental_proyectos: idi.impacto_ambiental_proyectos,
    })

    function submit() {
        if (idi.proyecto.allowed.to_update) {
            $form.post(route('convocatorias.idi.indicadores.store', [convocatoria.id, idi.id]))
        }
    }

    async function syncColumnLong(column, form) {
        return new Promise((resolve) => {
            if (typeof column !== undefined && typeof form !== undefined && idi.proyecto.allowed.to_update) {
                let value
                form[column] ? (value = form[column]) : (value = form)
                Inertia.put(
                    route('convocatorias.idi.updateLongColumn', [convocatoria.id, idi.id, column]),
                    { [column]: value },
                    {
                        onError: (resp) => resolve(resp),
                        onFinish: () => resolve({}),
                        preserveScroll: true,
                    },
                )
            } else {
                resolve({})
            }
        })
    }
</script>

<AuthenticatedLayout>
    <header class="pt-[8rem]" slot="header">
        <Stepper {convocatoria} proyecto={idi} />
    </header>

    <p class="text-center">Describa de forma general (en los que aplique) el aporte del proyecto a los indicadores de los proyectos relacionados en el artículo 5 del acuerdo 003 del 02 de febrero de 2012 (<strong>Mínimo debe relacionar uno</strong>).</p>

    <form on:submit|preventDefault={submit}>
        <fieldset class="p-8 divide-y" disabled={idi.proyecto.allowed.to_update ? undefined : true}>
            <div class="py-24 grid grid-cols-2">
                <div>
                    <Label class="mb-4" labelFor="productividad_beneficiaros" value="a) Productividad y competitividad del (los) beneficiario(s) final(es) del proyecto" />
                </div>
                <div>
                    <Textarea maxlength="40000" id="productividad_beneficiaros" error={errors.productividad_beneficiaros} bind:value={$form.productividad_beneficiaros} on:blur={() => syncColumnLong('productividad_beneficiaros', $form.productividad_beneficiaros)} />
                </div>
            </div>

            <div class="py-24 grid grid-cols-2">
                <div>
                    <Label class="mb-4" labelFor="generacion_empleo_beneficiarios" value="b) Generación o mantenimiento de empleo por parte del (los) beneficiario(s) del proyecto" />
                </div>
                <div>
                    <Textarea maxlength="40000" id="generacion_empleo_beneficiarios" error={errors.generacion_empleo_beneficiarios} bind:value={$form.generacion_empleo_beneficiarios} on:blur={() => syncColumnLong('generacion_empleo_beneficiarios', $form.generacion_empleo_beneficiarios)} />
                </div>
            </div>

            <div class="py-24 grid grid-cols-2">
                <div>
                    <Label class="mb-4" labelFor="creacion_nuevos_desarrollos" value=" c) Creación de nuevas empresas y diseño y desarrollo de nuevos productos, procesos o servicios" />
                </div>
                <div>
                    <Textarea maxlength="40000" id="creacion_nuevos_desarrollos" error={errors.creacion_nuevos_desarrollos} bind:value={$form.creacion_nuevos_desarrollos} on:blur={() => syncColumnLong('creacion_nuevos_desarrollos', $form.creacion_nuevos_desarrollos)} />
                </div>
            </div>

            <div class="py-24 grid grid-cols-2">
                <div>
                    <Label class="mb-4" labelFor="generacion_conocimientos_beneficiarios" value="d) Incorporación de nuevos conocimientos y competencias laborales en el talento humano en la(s) empresa(s) beneficiaria(s) del proyecto" />
                </div>
                <div>
                    <Textarea maxlength="40000" id="generacion_conocimientos_beneficiarios" error={errors.generacion_conocimientos_beneficiarios} bind:value={$form.generacion_conocimientos_beneficiarios} on:blur={() => syncColumnLong('generacion_conocimientos_beneficiarios', $form.generacion_conocimientos_beneficiarios)} />
                </div>
            </div>

            <div class="py-24 grid grid-cols-2">
                <div>
                    <Label class="mb-4" labelFor="generacion_valor_beneficiarios" value="e) Generación de valor agregado en la(s) entidad(es) beneficiaria(s) del proyecto" />
                </div>
                <div>
                    <Textarea maxlength="40000" id="generacion_valor_beneficiarios" error={errors.generacion_valor_beneficiarios} bind:value={$form.generacion_valor_beneficiarios} on:blur={() => syncColumnLong('generacion_valor_beneficiarios', $form.generacion_valor_beneficiarios)} />
                </div>
            </div>

            <div class="py-24 grid grid-cols-2">
                <div>
                    <Label class="mb-4" labelFor="fortalecimiento_programas_formacion" value="f) Fortalecimiento de programas de formación del Sena" />
                </div>
                <div>
                    <Textarea maxlength="40000" id="fortalecimiento_programas_formacion" error={errors.fortalecimiento_programas_formacion} bind:value={$form.fortalecimiento_programas_formacion} on:blur={() => syncColumnLong('fortalecimiento_programas_formacion', $form.fortalecimiento_programas_formacion)} />
                </div>
            </div>

            <div class="py-24 grid grid-cols-2">
                <div>
                    <Label class="mb-4" labelFor="transferencia_tecnologias" value="g) Transferencia de tecnologías al Sena y a los sectores productivos relacionados" />
                </div>
                <div>
                    <Textarea maxlength="40000" id="transferencia_tecnologias" error={errors.transferencia_tecnologias} bind:value={$form.transferencia_tecnologias} on:blur={() => syncColumnLong('transferencia_tecnologias', $form.transferencia_tecnologias)} />
                </div>
            </div>

            <div class="py-24 grid grid-cols-2">
                <div>
                    <Label class="mb-4" labelFor="calidad_formacion" value="h) Cobertura, calidad y pertinencia de la formación." />
                </div>
                <div>
                    <Textarea maxlength="40000" id="calidad_formacion" error={errors.calidad_formacion} bind:value={$form.calidad_formacion} on:blur={() => syncColumnLong('calidad_formacion', $form.calidad_formacion)} />
                </div>
            </div>

            <div class="py-24 grid grid-cols-2">
                <div>
                    <Label class="mb-4" labelFor="impacto_ambiental_proyectos" value="i) Impacto ambiental de Proyectos de Innovación e investigación aplicada. " />
                </div>
                <div>
                    <Textarea maxlength="40000" id="impacto_ambiental_proyectos" error={errors.impacto_ambiental_proyectos} bind:value={$form.impacto_ambiental_proyectos} on:blur={() => syncColumnLong('impacto_ambiental_proyectos', $form.impacto_ambiental_proyectos)} />
                </div>
            </div>

            <div class="shadow-inner bg-app-200 border-app-400 flex items-center justify-between mt-14 px-8 py-4">
                {#if idi.proyecto.allowed.to_update}
                    <LoadingButton loading={$form.processing} class="ml-auto" type="submit">
                        {$_('Save')}
                    </LoadingButton>
                {:else}
                    <span class="inline-block ml-1.5"> El recurso no se puede crear/modificar </span>
                {/if}
            </div>
        </fieldset>
    </form>
</AuthenticatedLayout>

// resources/js/Pages/Convocatorias/Proyectos/Indicadores/Index.jsx
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout'

import Label from '@/Components/Label'
import PrimaryButton from '@/Components/PrimaryButton'
import Textarea from '@/Components/Textarea'
import StepperMui from '@/Components/Stepper'

import { router, useForm } from '@inertiajs/react'
import { Grid } from '@mui/material'

const Indicadores = ({ auth, convocatoria, proyecto_linea_66, evaluacion, ...props }) => {
    const form = useForm({
        productividad_beneficiaros: proyecto_linea_66.productividad_beneficiaros ? proyecto_linea_66.productividad_beneficiaros : '',
        generacion_empleo_beneficiarios: proyecto_linea_66.generacion_empleo_beneficiarios ? proyecto_linea_66.generacion_empleo_beneficiarios : '',
        creacion_nuevos_desarrollos: proyecto_linea_66.creacion_nuevos_desarrollos ? proyecto_linea_66.creacion_nuevos_desarrollos : '',
        generacion_conocimientos_beneficiarios: proyecto_linea_66.generacion_conocimientos_beneficiarios ? proyecto_linea_66.generacion_conocimientos_beneficiarios : '',
        generacion_valor_beneficiarios: proyecto_linea_66.generacion_valor_beneficiarios ? proyecto_linea_66.generacion_valor_beneficiarios : '',
        fortalecimiento_programas_formacion: proyecto_linea_66.fortalecimiento_programas_formacion ? proyecto_linea_66.fortalecimiento_programas_formacion : '',
        transferencia_tecnologias: proyecto_linea_66.transferencia_tecnologias ? proyecto_linea_66.transferencia_tecnologias : '',
        calidad_formacion: proyecto_linea_66.calidad_formacion ? proyecto_linea_66.calidad_formacion : '',
        impacto_ambiental_proyectos: proyecto_linea_66.impacto_ambiental_proyectos ? proyecto_linea_66.impacto_ambiental_proyectos : '',
    })

    const submit = (e) => {
        e.preventDefault()
        if (proyecto_linea_66.proyecto.allowed.to_update) {
            form.post(route('convocatorias.proyectos-linea-66.indicadores.store', [convocatoria.id, proyecto_linea_66.id]))
        }
    }

    const syncColumnLong = async (column, form) => {
        if (typeof column !== 'undefined' && typeof form !== 'undefined' && proyecto_linea_66?.proyecto?.allowed?.to_update) {
            try {
                await router.put(
                    route('convocatorias.proyectos-linea-66.updateLongColumn', [convocatoria.id, proyecto_linea_66?.proyecto?.id, column]),
                    { [column]: form.data[column], is_array: Array.isArray(form.data[column]) },
                    {
                        onError: (resp) => console.log(resp),
                        onFinish: () => console.log('Request finished'),
                        preserveScroll: true,
                    },
                )
            } catch (error) {
                console.error('An error occurred:', error)
            }
        }
    }

    return (
        <AuthenticatedLayout>
            <Grid item md={12} className="!mb-20">
                <StepperMui convocatoria={convocatoria} proyecto={proyecto_linea_66.proyecto} evaluacion={evaluacion} />
            </Grid>

            <Grid item md={12} className="!mb-20">
                <p className="text-center">
                    Describa de forma general (en los que aplique) el aporte del proyecto a los indicadores de los proyectos relacionados en el artículo 5 del acuerdo 003 del 02 de febrero de 2012 (
                    <strong>Mínimo debe relacionar uno</strong>).
                </p>

                <form onSubmit={submit}>
                    <fieldset className="p-8 divide-y" disabled={proyecto_linea_66.proyecto.allowed.to_update ? false : true}>
                        <div className="py-24 grid grid-cols-2">
                            <div>
                                <Label className="mb-4" labelFor="productividad_beneficiaros" value="a) Productividad y competitividad del (los) beneficiario(s) final(es) del proyecto" />
                            </div>
                            <div>
                                <Textarea
                                    id="productividad_beneficiaros"
                                    error={form.errors.productividad_beneficiaros}
                                    value={form.data.productividad_beneficiaros}
                                    onChange={(e) => form.setData('productividad_beneficiaros', e.target.value)}
                                    onBlur={() => syncColumnLong('productividad_beneficiaros', form)}
                                />
                            </div>
                        </div>

                        <div className="py-24 grid grid-cols-2">
                            <div>
                                <Label className="mb-4" labelFor="generacion_empleo_beneficiarios" value="b) Generación o mantenimiento de empleo por parte del (los) beneficiario(s) del proyecto" />
                            </div>
                            <div>
                                <Textarea
                                    id="generacion_empleo_beneficiarios"
                                    error={form.errors.generacion_empleo_beneficiarios}
                                    value={form.data.generacion_empleo_beneficiarios}
                                    onChange={(e) => form.setData('generacion_empleo_beneficiarios', e.target.value)}
                                    onBlur={() => syncColumnLong('generacion_empleo_beneficiarios', form)}
                                />
                            </div>
                        </div>

                        <div className="py-24 grid grid-cols-2">
                            <div>
                                <Label
                                    className="mb-4"
                                    labelFor="creacion_nuevos_desarrollos"
                                    value=" c) Creación de nuevas empresas y diseño y desarrollo de nuevos productos, procesos o servicios"
                                />
                            </div>
                            <div>
                                <Textarea
                                    id="creacion_nuevos_desarrollos"
                                    error={form.errors.creacion_nuevos_desarrollos}
                                    value={form.data.creacion_nuevos_desarrollos}
                                    onChange={(e) => form.setData('creacion_nuevos_desarrollos', e.target.value)}
                                    onBlur={() => syncColumnLong('creacion_nuevos_desarrollos', form)}
                                />
                            </div>
                        </div>

                        <div className="py-24 grid grid-cols-2">
                            <div>
                                <Label
                                    className="mb-4"
                                    labelFor="generacion_conocimientos_beneficiarios"
                                    value="d) Incorporación de nuevos conocimientos y competencias laborales en el talento humano en la(s) empresa(s) beneficiaria(s) del proyecto"
                                />
                            </div>
                            <div>
                                <Textarea
                                    id="generacion_conocimientos_beneficiarios"
                                    error={form.errors.generacion_conocimientos_beneficiarios}
                                    value={form.data.generacion_conocimientos_beneficiarios}
                                    onChange={(e) => form.setData('generacion_conocimientos_beneficiarios', e.target.value)}
                                    onBlur={() => syncColumnLong('generacion_conocimientos_beneficiarios', form)}
                                />
                            </div>
                        </div>

                        <div className="py-24 grid grid-cols-2">
                            <div>
                                <Label className="mb-4" labelFor="generacion_valor_beneficiarios" value="e) Generación de valor agregado en la(s) entidad(es) beneficiaria(s) del proyecto" />
                            </div>
                            <div>
                                <Textarea
                                    id="generacion_valor_beneficiarios"
                                    error={form.errors.generacion_valor_beneficiarios}
                                    value={form.data.generacion_valor_beneficiarios}
                                    onChange={(e) => form.setData('generacion_valor_beneficiarios', e.target.value)}
                                    onBlur={() => syncColumnLong('generacion_valor_beneficiarios', form)}
                                />
                            </div>
                        </div>

                        <div className="py-24 grid grid-cols-2">
                            <div>
                                <Label className="mb-4" labelFor="fortalecimiento_programas_formacion" value="f) Fortalecimiento de programas de formación del Sena" />
                            </div>
                            <div>
                                <Textarea
                                    id="fortalecimiento_programas_formacion"
                                    error={form.errors.fortalecimiento_programas_formacion}
                                    value={form.data.fortalecimiento_programas_formacion}
                                    onChange={(e) => form.setData('fortalecimiento_programas_formacion', e.target.value)}
                                    onBlur={() => syncColumnLong('fortalecimiento_programas_formacion', form)}
                                />
                            </div>
                        </div>

                        <div className="py-24 grid grid-cols-2">
                            <div>
                                <Label className="mb-4" labelFor="transferencia_tecnologias" value="g) Transferencia de tecnologías al Sena y a los sectores productivos relacionados" />
                            </div>
                            <div>
                                <Textarea
                                    id="transferencia_tecnologias"
                                    error={form.errors.transferencia_tecnologias}
                                    value={form.data.transferencia_tecnologias}
                                    onChange={(e) => form.setData('transferencia_tecnologias', e.target.value)}
                                    onBlur={() => syncColumnLong('transferencia_tecnologias', form)}
                                />
                            </div>
                        </div>

                        <div className="py-24 grid grid-cols-2">
                            <div>
                                <Label className="mb-4" labelFor="calidad_formacion" value="h) Cobertura, calidad y pertinencia de la formación." />
                            </div>
                            <div>
                                <Textarea
                                    id="calidad_formacion"
                                    error={form.errors.calidad_formacion}
                                    value={form.data.calidad_formacion}
                                    onChange={(e) => form.setData('calidad_formacion', e.target.value)}
                                    onBlur={() => syncColumnLong('calidad_formacion', form)}
                                />
                            </div>
                        </div>

                        <div className="py-24 grid grid-cols-2">
                            <div>
                                <Label className="mb-4" labelFor="impacto_ambiental_proyectos" value="i) Impacto ambiental de Proyectos de Innovación e investigación aplicada. " />
                            </div>
                            <div>
                                <Textarea
                                    id="impacto_ambiental_proyectos"
                                    error={form.errors.impacto_ambiental_proyectos}
                                    value={form.data.impacto_ambiental_proyectos}
                                    onChange={(e) => form.setData('impacto_ambiental_proyectos', e.target.value)}
                                    onBlur={() => syncColumnLong('impacto_ambiental_proyectos', form)}
                                />
                            </div>
                        </div>

                        <div className="flex items-center justify-between mt-14 py-4">
                            {proyecto_linea_66.proyecto.allowed.to_update ? (
                                <PrimaryButton disabled={form.processing} className="ml-auto" type="submit">
                                    Guardar
                                </PrimaryButton>
                            ) : (
                                <span className="inline-block ml-1.5"> El recurso no se puede crear/modificar </span>
                            )}
                        </div>
                    </fieldset>
                </form>
            </Grid>
        </AuthenticatedLayout>
    )
}

export default Indicadores
