// resources/js/Pages.bak/Pages/Auth/ForgotPassword.svelte
<script context="module">
    import GuestLayout from '@/Layouts/Guest'
    export const layout = GuestLayout
</script>

<script>
    import { page, inertia, useForm } from '@inertiajs/inertia-svelte'
    import { route, checkRole, checkPermission } from '@/Utils'
    import { _ } from 'svelte-i18n'

    import LoadingButton from '@/Shared/LoadingButton'
    import Input from '@/Shared/Input'
    import InfoMessage from '@/Shared/InfoMessage'

    export let success
    export let error
    export let errors

    let form = useForm({
        email: '',
        numero_documento: '',
    })

    function handleSubmit() {
        $form.post(route('password.email'))
    }
</script>

{#if success}
    <div class="mb-4 font-medium text-sm text-green-600">
        {success}
    </div>
{:else if error}
    <div class="mb-4 font-medium text-sm text-red-600">
        {error}
    </div>
{/if}

<form on:submit|preventDefault={handleSubmit} class="m-10 w-2/3">
    <div>
        <Input label={$_('Email')} id="email" type="email" class="mt-1" bind:value={$form.email} error={errors.email} name="email" required autocomplete="email" />
    </div>

    <div class="mt-4">
        <Input label="Número de documento" id="numero_documento" type="number" class="mt-1" bind:value={$form.numero_documento} error={errors.numero_documento} name="numero_documento" required />
    </div>

    {#if $page.props.flash.success}
        <div>
            <InfoMessage class="ml-4 text-center">
                La nueva contraseña es: <strong>sena{$form.numero_documento}*</strong>
                <br />
                <a use:inertia href="/" class="p-3 block rounded text-center mt-2 bg-app-700 text-white">Volver al inico de sesión</a>
            </InfoMessage>
        </div>
    {/if}

    <div class="flex items-center justify-end mt-4">
        <LoadingButton loading={$form.processing} type="submit">Restablecer contraseña</LoadingButton>
    </div>
</form>

// resources/js/Pages/Auth/ForgotPassword.jsx
import GuestLayout from '@/Layouts/GuestLayout';
import InputError from '@/Components/InputError';
import PrimaryButton from '@/Components/PrimaryButton';
import TextInput from '@/Components/TextInput';
import { Head, useForm } from '@inertiajs/react';

export default function Login({ status }) {
    const { data, setData, post, processing, errors, reset } = useForm({
        email: '',
        numero_documento: '',
    });

    const submit = (e) => {
        e.preventDefault();

        post(route('password.email'))
    };

    return (
        <GuestLayout>
            <Head title="Restablecer contraseña" />

            {status && <div className="mb-4 font-medium text-sm text-green-600">{status}</div>}

            <p className="mt-10 text-gray-500 text-justify">¿Ha olvidado su contraseña? No se preocupe. Díganos su correo electrónico institucional y número de documento. Si los datos coinciden se restablecerá su contraseña y esta será su número de documento.</p>

            <form onSubmit={submit} className="w-[22rem] my-10 relative">
                <div>
                    <TextInput
                        id="email"
                        type="email"
                        name="email"
                        label="Correo electrónico SENA"
                        required
                        value={data.email}
                        className="mt-1 block w-full"
                        autoComplete="email"
                        isFocused={true}
                        onChange={(e) => setData('email', e.target.value)}
                    />

                    <InputError message={errors.email} className="mt-2" />
                </div>

                <div className="mt-4">
                    <TextInput
                        id="numero_documento"
                        type="number"
                        name="numero_documento"
                        label="Número de documento"
                        required
                        value={data.numero_documento}
                        className="mt-1 block w-full"
                        autoComplete="current-numero_documento"
                        onChange={(e) => setData('numero_documento', e.target.value)}
                    />

                    <InputError message={errors.numero_documento} className="mt-2" />
                </div>

                <div className="flex items-center justify-end mt-4">
                    <PrimaryButton className="ml-4" disabled={processing}>
                        Restablecer contraseña
                    </PrimaryButton>
                </div>
            </form>
        </GuestLayout>
    )
}
