// resources/js/Pages/Auth/Register.svelte
<script context="module">
    import GuestLayout from '@/Layouts/Guest'
    export const layout = GuestLayout
</script>

<script>
    import { inertia, useForm } from '@inertiajs/inertia-svelte'
    import { route, checkRole, checkPermission } from '@/Utils'
    import { _ } from 'svelte-i18n'
    import LoadingButton from '@/Shared/LoadingButton'
    import Input from '@/Shared/Input'
    import Label from '@/Shared/Label'
    import InputError from '@/Shared/InputError'
    import Select from '@/Shared/Select'
    import InfoMessage from '@/Shared/InfoMessage'
    import Checkbox from '@smui/checkbox'
    import FormField from '@smui/form-field'

    export let errors
    export let tiposDocumento
    export let tiposVinculacion
    export let roles
    export let centrosFormacion
    export let municipios
    export let opcionesGenero
    export let user

    let form = useForm({
        nombre: '',
        email: '',
        password: '',
        password_confirmation: '',
        tipo_documento: '',
        numero_documento: '',
        lugar_expedicion_id: '',
        genero: '',
        fecha_nacimiento: '',
        numero_celular: '',
        tipo_vinculacion: '',
        centro_formacion_id: null,
        autorizacion_datos: false,
        role_id: [],
    })

    function handleSubmit() {
        if ($form.autorizacion_datos) {
            $form.post(route('register'))
        }
    }
</script>

<form on:submit|preventDefault={handleSubmit} class="mt-20">
    {#if user}
        <InfoMessage>
            El usuario con número de documento {user.numero_documento} ya está registrado en el sistema. Por favor inicie sesión haciendo <a use:inertia href="/" class="underline">clic aquí</a>. Si no recuerda la contraseña la puede recuperar en el siguiente enlace <a use:inertia href="/forgot-password" class="underline">Recuperar contraseña</a>
        </InfoMessage>
    {/if}
    <div>
        <Input label="Nombre completo" id="nombre" type="text" class="mt-1" bind:value={$form.nombre} error={errors.nombre} required autocomplete="nombre" />
    </div>

    <div class="mt-8">
        <Input label="Correo electrónico institucional" id="email" type="email" class="mt-1" bind:value={$form.email} error={errors.email} required autocomplete="username" />
        {#if errors.email == 'El campo correo electrónico ya ha sido tomado.'}
            <InfoMessage alertMsg={true} class="mt-4">
                <p class="mt-3 py-4 text-justify">
                    El correo electrónico ya fue registrado, Por favor inicie sesión haciendo <a use:inertia href="/" class="underline">clic aquí</a>. Si no recuerda la contraseña la puede recuperar en el siguiente enlace <a use:inertia href="/forgot-password" class="underline">Recuperar contraseña</a>
                </p>
            </InfoMessage>
        {/if}
    </div>

    <div class="mt-8">
        <Input label={$_('Password')} id="password" type="password" class="mt-1" bind:value={$form.password} error={errors.password} required autocomplete="new-password" />
    </div>

    <div class="mt-8">
        <Input label={$_('Confirm Password')} id="password_confirmation" type="password" class="mt-1" bind:value={$form.password_confirmation} error={errors.password_confirmation} required autocomplete="new-password" />
    </div>

    <div class="mt-8">
        <Label required class="mb-4" labelFor="tipo_documento" value="Tipo de documento" />
        <Select id="tipo_documento" items={tiposDocumento} bind:selectedValue={$form.tipo_documento} error={errors.tipo_documento} autocomplete="off" placeholder="Seleccione un tipo de documento" required />
    </div>

    <div class="mt-8">
        <Input label="Número de documento" id="numero_documento" type="number" input$min="55555" input$max="3900000000" class="mt-1" bind:value={$form.numero_documento} error={errors.numero_documento} required />
    </div>

    <div class="mt-8">
        <Label required class="mb-4" labelFor="lugar_expedicion_id" value="Lugar de expedición" />
        <Select id="lugar_expedicion_id" items={municipios} bind:selectedValue={$form.lugar_expedicion_id} error={errors.lugar_expedicion_id} autocomplete="off" placeholder="Seleccione una opción" required />
    </div>

    <div class="mt-8">
        <Label required class="mb-4" labelFor="genero" value="Género" />
        <Select id="genero" items={opcionesGenero} bind:selectedValue={$form.genero} error={errors.genero} autocomplete="off" placeholder="Seleccione una opción" required />
    </div>

    <div class="mt-8">
        <Label labelFor="fecha_nacimiento" value="Fecha de nacimiento" />
        <input id="fecha_nacimiento" type="date" class="mt-1 block w-full p-4" error={errors.fecha_nacimiento} bind:value={$form.fecha_nacimiento} required />
    </div>

    <div class="mt-8">
        <Input label="Número de celular" id="numero_celular" type="number" input$min="3000000000" input$max="3900000000" class="mt-1" bind:value={$form.numero_celular} error={errors.numero_celular} required />
    </div>

    <div class="mt-8">
        <Label required class="mb-4" labelFor="tipo_vinculacion" value="Tipo de vinculación" />
        <Select id="tipo_vinculacion" items={tiposVinculacion} bind:selectedValue={$form.tipo_vinculacion} error={errors.tipo_vinculacion} autocomplete="off" placeholder="Seleccione el tipo de vinculación" required />
    </div>

    <div class="mt-8">
        <Label required class="mb-4" labelFor="centro_formacion_id" value="Centro de formación" />
        <Select id="centro_formacion_id" items={centrosFormacion} bind:selectedValue={$form.centro_formacion_id} error={errors.centro_formacion_id} autocomplete="off" placeholder="Busque por el nombre del centro de formación" required />
    </div>

    <div class="mt-8">
        <Label required class="mb-4" labelFor="role_id" value="Seleccione algún rol" />
        <InputError message={errors.role_id} />
    </div>
    <div class="grid grid-cols-2">
        {#each roles as { id, name }, i}
            <FormField class="mt-2 border-r border-t">
                <Checkbox bind:group={$form.role_id} value={id} />
                <span slot="label" class="first-letter-uppercase inline-block">{name}</span>
            </FormField>
        {/each}
    </div>

    <hr class="mt-4" />

    <div class="block mt-4">
        <InfoMessage class="shadow ml-4 mb-4" message="Los datos proporcionados serán tratados de acuerdo con la política de tratamiento de datos personales del SENA y a la ley 1581 de 2012 (Acuerdo No. 0009 del 2016)" />
        <FormField>
            <Checkbox bind:checked={$form.autorizacion_datos} />
            <span slot="label">Autorizo el tratamiento de mis datos personales. <a href="https://www.sena.edu.co/es-co/transparencia/Documents/proteccion_datos_personales_sena_2016.pdf" target="_blank" class="text-app-500">Leer acuerdo No. 0009 del 2016</a></span>
        </FormField>
    </div>

    <div class="flex items-center justify-end mt-4">
        <a use:inertia href={route('login')} class="mr-4 underline text-sm text-gray-600 hover:text-gray-900">
            {$_('Already registered?')}
        </a>

        <LoadingButton loading={$form.processing} type="submit" bind:disabled={$form.autorizacion_datos}>Continuar</LoadingButton>
    </div>
</form>

// resources/js/Pages/Auth/Register.jsx
import GuestLayout from '@/Layouts/GuestLayout'

import AlertMui from '@/Components/Alert'
import Autocomplete from '@/Components/Autocomplete'
import Checkbox from '@/Components/Checkbox'
import DatePicker from '@/Components/DatePicker'
import PasswordInput from '@/Components/PasswordInput'
import PrimaryButton from '@/Components/PrimaryButton'
import TextInput from '@/Components/TextInput'

import { Head, Link, useForm } from '@inertiajs/react'

export default function Login({ tiposDocumento, tiposVinculacion, roles, centrosFormacion, municipios, opcionesGenero, user, status, ...props }) {
    const { data, setData, post, processing, errors, reset } = useForm({
        nombre: user?.nombre,
        email: user?.email,
        password: user?.password,
        password_confirmation: user?.password_confirmation,
        tipo_documento: user?.tipo_documento,
        numero_documento: user?.numero_documento,
        lugar_expedicion_id: user?.lugar_expedicion_id,
        genero: user?.genero,
        fecha_nacimiento: user?.fecha_nacimiento,
        numero_celular: user?.numero_celular,
        tipo_vinculacion: user?.tipo_vinculacion,
        centro_formacion_id: user?.centro_formacion_id,
        autorizacion_datos: user?.autorizacion_datos ?? false,
    })

    const submit = (e) => {
        e.preventDefault()

        post(route('register'))
    }

    return (
        <GuestLayout>
            <Head title="Registro" />

            {status && <AlertMui error={props.flash?.error}>{status}</AlertMui>}

            {user && (
                <AlertMui>
                    El usuario con número de documento {user.numero_documento} ya está registrado en el sistema. Por favor inicie sesión haciendo. Si no recuerda la contraseña la puede recuperar en la
                    opcion: Recuperar contraseña.
                </AlertMui>
            )}
            <form onSubmit={submit} className="mt-20 w-[22rem]">
                <div>
                    <TextInput
                        label="Nombre completo"
                        id="nombre"
                        type="text"
                        className="mt-1 w-full"
                        value={data.nombre}
                        error={errors.nombre}
                        onChange={(e) => setData('nombre', e.target.value)}
                        required
                    />
                </div>

                <div className="mt-8 relative">
                    <TextInput
                        label="Correo electrónico institucional"
                        id="email"
                        type="email"
                        className="mt-1 w-full"
                        value={data.email}
                        error={errors.email}
                        onChange={(e) => setData('email', e.target.value)}
                        required
                    />
                    {errors.email == 'El campo correo electrónico ya ha sido tomado.' && (
                        <AlertMui severity="error">
                            El correo electrónico ya fue registrado, Por favor inicie sesión haciendo{' '}
                            <Link href="/" className="underline">
                                clic aquí
                            </Link>
                            . Si no recuerda la contraseña la puede recuperar en el siguiente enlace{' '}
                            <Link href="/forgot-password" className="underline">
                                Recuperar contraseña
                            </Link>
                        </AlertMui>
                    )}
                </div>

                <div className="mt-8">
                    <PasswordInput
                        label="Contraseña"
                        id="password"
                        type="password"
                        className="mt-1 w-full"
                        value={data.password}
                        error={errors.password}
                        onChange={(e) => setData('password', e.target.value)}
                        required
                    />
                </div>

                <div className="mt-8">
                    <PasswordInput
                        label="Confirmar contraseña"
                        id="password_confirmation"
                        type="password"
                        className="mt-1 w-full"
                        value={data.password_confirmation}
                        error={errors.password_confirmation}
                        onChange={(e) => setData('password_confirmation', e.target.value)}
                        required
                    />
                </div>

                <div className="mt-8">
                    <Autocomplete
                        id="tipo_documento"
                        options={tiposDocumento}
                        selectedValue={data.tipo_documento}
                        error={errors.tipo_documento}
                        onChange={(event, newValue) => {
                            setData('tipo_documento', newValue.value)
                        }}
                        label="Tipo de documento"
                        required
                    />
                </div>

                <div className="mt-8">
                    <TextInput
                        label="Número de documento"
                        id="numero_documento"
                        type="number"
                        min="55555"
                        max="3900000000"
                        className="mt-1 w-full"
                        value={data.numero_documento}
                        error={errors.numero_documento}
                        onChange={(e) => setData('numero_documento', e.target.value)}
                        required
                    />
                </div>

                <div className="mt-8">
                    <Autocomplete
                        id="lugar_expedicion_id"
                        options={municipios}
                        selectedValue={data.lugar_expedicion_id}
                        error={errors.lugar_expedicion_id}
                        onChange={(event, newValue) => {
                            setData('lugar_expedicion_id', newValue.value)
                        }}
                        label="Lugar de expedición"
                        required
                    />
                </div>

                <div className="mt-8">
                    <Autocomplete
                        id="genero"
                        options={opcionesGenero}
                        className="mt-1 w-full"
                        selectedValue={data.genero}
                        error={errors.genero}
                        onChange={(event, newValue) => {
                            setData('genero', newValue.value)
                        }}
                        label="Género"
                        required
                    />
                </div>

                <div className="mt-8">
                    <DatePicker
                        variant="outlined"
                        id="fecha_nacimiento"
                        name="fecha_nacimiento"
                        label="Fecha de nacimiento"
                        value={data.fecha_nacimiento}
                        className="p-4 w-full"
                        onChange={(e) => setData({ ...data, fecha_nacimiento: e.target.value })}
                        required
                    />
                </div>

                <div className="mt-8">
                    <TextInput
                        label="Número de celular"
                        id="numero_celular"
                        type="number"
                        min="3000000000"
                        max="3900000000"
                        className="mt-1 w-full"
                        value={data.numero_celular}
                        error={errors.numero_celular}
                        onChange={(e) => setData('numero_celular', e.target.value)}
                        required
                    />
                </div>

                <div className="mt-8">
                    <Autocomplete
                        id="tipo_vinculacion"
                        options={tiposVinculacion}
                        selectedValue={data.tipo_vinculacion}
                        error={errors.tipo_vinculacion}
                        onChange={(event, newValue) => {
                            setData('tipo_vinculacion', newValue.value)
                        }}
                        label="Tipo de vinculación"
                        required
                    />
                </div>

                <div className="mt-8">
                    <Autocomplete
                        id="centro_formacion_id"
                        options={centrosFormacion}
                        selectedValue={data.centro_formacion_id}
                        error={errors.centro_formacion_id}
                        onChange={(event, newValue) => {
                            setData('centro_formacion_id', newValue.value)
                        }}
                        label="Centro de formación"
                        required
                    />
                </div>

                <div className="block mt-8">
                    <AlertMui>
                        Los datos proporcionados serán tratados de acuerdo con la política de tratamiento de datos personales del SENA y a la ley 1581 de 2012 (Acuerdo No. 0009 del 2016)
                    </AlertMui>

                    <Checkbox
                        className="mt-8"
                        name="autorizacion_datos"
                        checked={data.autorizacion_datos}
                        error={errors.autorizacion_datos}
                        onChange={(e) => setData('autorizacion_datos', e.target.checked)}
                        label="Autorizo el tratamiento de mis datos personales."
                    />
                </div>

                <div className="flex options-center justify-end mt-4">
                    <Link href={route('login')} className="mr-4 underline text-sm text-gray-600 hover:text-gray-900">
                        Ya tengo una cuenta
                    </Link>

                    <PrimaryButton type="submit" disabled={processing || !data.autorizacion_datos}>
                        Continuar
                    </PrimaryButton>
                </div>
            </form>
        </GuestLayout>
    )
}
