// resources/js/Pages/Convocatorias/Edit.jsx
import { useForm } from '@inertiajs/react';
import { route, checkRole } from '@/Utils';

import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import Label from '@/Components/Label';
// import InputError from '@/Components/InputError';
import PrimaryButton from '@/Components/PrimaryButton';
import Textarea from '@/Components/Textarea';
import Switch from '@/Components/Switch';
import Autocomplete from '@/Components/Autocomplete';
import MultipleSelect from '@/Components/MultipleSelect';

const EditConvocatoria = ({ auth, errors, convocatoria, lineas_programaticas, lineas_programaticas_activas_relacionadas, fases }) => {

  // Validar si el usuario autenticado es SuperAdmin
  const authUser = auth.user;
  const isSuperAdmin = checkRole(authUser, [1]);

    const submitFase = (e) => {
        e.preventDefault();

        postFase(route('convocatorias.update-fase', convocatoria.id))
    };

const { data: dataFase, setData: setDataFase, post: postFase, processing: processingFase, errors: errorsFase, reset: resetFase } = useForm({
    fase: convocatoria.fase,
    fecha_finalizacion_fase: convocatoria.fecha_finalizacion_fase,
    hora_finalizacion_fase: convocatoria.hora_finalizacion_fase,
  });

  const { data: dataConvocatoria, setData: setDataConvocatoria, post: postConvocatoria, processing: processingConvocatoria, errors: errorsConvocatoria, reset: resetConvocatoria } = useForm({
    descripcion: convocatoria.descripcion,
    esta_activa: convocatoria.esta_activa,
    visible: convocatoria.visible,
    mostrar_recomendaciones: convocatoria.mostrar_recomendaciones,
    lineas_programaticas_activas: lineas_programaticas_activas_relacionadas.length > 0 ? lineas_programaticas_activas_relacionadas : null,
  });

  const submitInfo = () => {
    if (isSuperAdmin) {
      postConvocatoria(route('convocatorias.update', convocatoria.id), {
        preserveScroll: true,
      });
    }
  };

  return (
    <AuthenticatedLayout
        user={auth.user}
        header={<h2 className="font-semibold text-xl text-gray-800 leading-tight">Lista de convocatorias</h2>}
    >
      <header className="pt-[8rem]" slot="header">
        <div className="flex items-center justify-between lg:px-8  px-4 py-6">
          <div>
            <h1 className="overflow-ellipsis overflow-hidden w-breadcrumb-ellipsis whitespace-nowrap">
              <a href={route('convocatorias.index')} className="text-app-400 hover:text-app-600">Convocatorias</a>
              <span className="text-app-400 font-medium">/</span>
              <a href={route('convocatorias.lineas-programaticas.index', convocatoria.id)} className="text-app-400 hover:text-app-600">
                {convocatoria.descripcion}
              </a>
            </h1>
          </div>
        </div>
      </header>

      <div className="grid grid-cols-3">
        <div>
          <h1 className="font-black text-4xl uppercase">Editar convocatoria</h1>
        </div>
        <div className="col-span-2">
          {convocatoria.tipo_convocatoria == 1 || convocatoria.tipo_convocatoria == 3 ? (
            <form onSubmit={submitFase} className="bg-white rounded shadow">
              <fieldset className="p-8" disabled={isSuperAdmin ? undefined : true}>
                <div className="grid grid-cols-2">
                  <div>
                    <Label required className="mb-4" labelFor="fase" value="Fase" />
                  </div>
                  <div>
                    <Autocomplete id="fase" items={fases} value={dataFase.fase} onChange={(e) => setDataFase('fase', e.target.value)} error={errors.fase} autoComplete={false} placeholder="Seleccione una fase" required />
                  </div>

                  {dataFase.fase?.label && (
                    <>
                      <div>
                        <Label required labelFor="fecha_finalizacion_fase" value={`Fecha de finalización de la fase: ${dataFase.fase.label.toLowerCase()}`} />
                      </div>
                      <div>
                        <input id="fecha_finalizacion_fase" type="date" className="mt-1 p-2" value={dataFase.fecha_finalizacion_fase} onChange={(e) => setDataFase('fecha_finalizacion_fase', e.target.value)} required />
                      </div>
                    </>
                  )}

                  <div>
                    <Label required labelFor="hora_finalizacion_fase" value="Hora límite" />
                  </div>
                  <div>
                    <input id="hora_finalizacion_fase" type="time" step="1" className="mt-1 p-2 border rounded border-gray-300" value={dataFase.hora_finalizacion_fase} onChange={(e) => setDataFase('hora_finalizacion_fase', e.target.value)} required />
                  </div>
                </div>

                <p className="mt-10">
                  {dataFase.fase?.value === 1 && (
                    <>
                      <strong>Tenga en cuenta:</strong> La fase de {dataFase.fase.label.toLowerCase()} permitirá a los formuladores crear, modificar y eliminar proyectos.
                    </>
                  )}
                  {dataFase.fase?.value === 2 && (
                    <>
                      <strong>Tenga en cuenta:</strong> La fase de {dataFase.fase.label.toLowerCase()} bloqueará a los formuladores las acciones de crear, modificar y eliminar proyectos.
                    </>
                  )}
                  {dataFase.fase?.value === 3 && (
                    <>
                      <strong>Tenga en cuenta:</strong> La fase de {dataFase.fase.label.toLowerCase()} permitirá a los formuladores modificar aquellos proyectos que pueden ser subsanados y a los evaluadores se le bloqueará la acción de modificar las evaluaciones.
                    </>
                  )}
                  {dataFase.fase?.value === 4 && (
                    <>
                      <strong>Tenga en cuenta:</strong> La fase de {dataFase.fase.label.toLowerCase()} bloqueará a los formuladores la acción de modificar aquellos proyectos que pasaron a etapa de subsanación y a los evaluadores se le habilitarán aquellas evaluaciones de proyectos subsanados.
                    </>
                  )}
                  {dataFase.fase?.value === 5 && (
                    <>
                      <strong>Tenga en cuenta:</strong> La fase de {dataFase.fase.label.toLowerCase()} bloqueará a los formuladores la modificación de proyectos y a los evaluadores la modificación de las evaluaciones.
                    </>
                  )}
                </p>
              </fieldset>
              <div className="shadow-inner bg-app-200 border-app-400 bottom-0 flex items-center justify-between mt-14 px-8 py-4 sticky">
                {isSuperAdmin && (
                  <PrimaryButton className="ml-auto" type="submit" disabled={processingFase}>
                    Editar fase
                  </PrimaryButton>
                )}
              </div>
            </form>
          ) : null}
        </div>

        <div className="bg-white rounded shadow">
          <form onSubmit={submitInfo}>
            <fieldset className="p-8" disabled={isSuperAdmin ? undefined : true}>
              <div className="mt-8">
                <Textarea label="Descripción" maxlength="40000" id="descripcion" error={errors.descripcion} value={dataConvocatoria.descripcion} onChange={(e) => setDataConvocatoria('descripcion', e.target.value)} required />
              </div>

              <div className="mt-10 mb-20">
                <Label required labelFor="esta_activa" value="¿Desea activar esta convocatoria? (Si la opción está habilitada permite a los usuarios formular proyectos. Tenga en cuenta que solo puede activar una convocatoria por tipo --Proyectos de convocatoria - Proyectos de ejecicio DEMO)" className="inline-block mb-4" />
                <br />
                <Switch checked={dataConvocatoria.esta_activa} onChange={(e) => setDataConvocatoria('esta_activa', e.target.checked)} />
              </div>

              <div>
                <div className="mt-10 mb-20">
                  <Label required labelFor="lineas_programaticas_activas" className="mb-4" value="Seleccione las líneas programáticas las cuales quiere activar" />
                  <MultipleSelect id="lineas_programaticas_activas" selectedValue={dataConvocatoria.lineas_programaticas_activas} onChange={(e) => setDataConvocatoria('lineas_programaticas_activas', e.target.value)} items={lineas_programaticas} isMulti={true} error={errors.lineas_programaticas_activas} placeholder="Seleccione las líneas programáticas" required />
                </div>
              </div>

              <div className="mt-10 mb-20">
                <Label required labelFor="visible" value="Defina la visibilidad de la convocatoria. (Si la opción está habilitada permite a los usuarios visualizar la convocatoria)" className="inline-block mb-4" />
                <br />
                <Switch checked={dataConvocatoria.visible} onChange={(e) => setDataConvocatoria('visible', e.target.checked)} onMessage="Visible" offMessage="Oculta" />
              </div>

              {(convocatoria.tipo_convocatoria == 1 || convocatoria.tipo_convocatoria == 3) && (
                <div className="mt-4 mb-20">
                  <Label required labelFor="mostrar_recomendaciones" value="¿Desea que el formulador visualice las recomendaciones hechas por los evaluadores?" className="inline-block mb-4" />
                  <br />
                  <Switch checked={dataConvocatoria.mostrar_recomendaciones} onChange={(e) => setDataConvocatoria('mostrar_recomendaciones', e.target.checked)} />
                </div>
              )}
            </fieldset>
            <div className="shadow-inner bg-app-200 border-app-400 flex items-center justify-between mt-14 px-8 py-4">
              {convocatoria && (
                <small className="flex items-center text-app-700">
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8" />
                  </svg>
                  Si no desea hacer cambios en los datos, puede dejar el formulario en blanco.
                </small>
              )}

              {isSuperAdmin && (
                <PrimaryButton type="submit" disabled={processingConvocatoria}>
                  Editar convocatoria
                </PrimaryButton>
              )}
            </div>
          </form>
        </div>
      </div>
    </AuthenticatedLayout>
  );
};

export default EditConvocatoria;

// resources/js/Pages/Proyectos/Edit.jsx
<script>
    import AuthenticatedLayout, { title } from '@/Layouts/Authenticated'
    import { inertia, useForm, page } from '@inertiajs/inertia-svelte'
    import { route, checkRole } from '@/Utils'
    import { _ } from 'svelte-i18n'

    import Label from '@/Components/Label'
    import Input from '@/Components/Input'
    import InputError from '@/Components/InputError'
    import PrimaryButton from '@/Components/PrimaryButton'
    import Switch from '@/Components/Switch'
    import InfoMessage from '@/Components/InfoMessage'
    import Button from '@/Components/Button'
    import Select from '@/Components/Select'
    import Dialog from '@/Components/Dialog'

    export let errors
    export let proyecto
    export let evaluadores

    $: $title = proyecto ? proyecto.codigo : null

    /**
     * Validar si el usuario autenticado es SuperAdmin
     */
    let authUser = auth.user
    let isSuperAdmin = checkRole(authUser, [1])

    let form = useForm({
        subsanacion: proyecto.habilitado_para_evaluar == false && proyecto.modificable == true && proyecto.finalizado == false,
        estado_cord_sennova: proyecto.estado_cord_sennova ? JSON.parse(proyecto.estado_cord_sennova)?.estado : null,
        mostrar_recomendaciones: proyecto.mostrar_recomendaciones,
        en_evaluacion: proyecto.en_evaluacion,
        radicado: proyecto.radicado,
    })

    function submit() {
        if (isSuperAdmin || checkRole(authUser, [20, 18, 19, 5, 17])) {
            $form.put(route('proyectos.update', proyecto.id), {
                preserveScroll: true,
            })
        }
    }

    let formEvaluacion = useForm({
        id: null,
        habilitado: false,
        modificable: false,
        finalizado: false,
        proyecto_id: null,
        user_id: null,
    })

    function submitEvaluacion() {
        if (isSuperAdmin || checkRole(authUser, [20, 18, 19, 5, 17])) {
            $formEvaluacion.put(route('evaluaciones.update', $formEvaluacion.id), {
                preserveScroll: true,
            })
        }
    }

    let dialogOpen = false
    let showEvaluacionForm = false
    function showEvaluacionDialog(evaluacion) {
        showEvaluacionForm = true
        dialogOpen = true
        $formEvaluacion.id = evaluacion.id
        $formEvaluacion.habilitado = evaluacion.habilitado
        $formEvaluacion.modificable = evaluacion.modificable
        $formEvaluacion.finalizado = evaluacion.finalizado
        $formEvaluacion.clausula_confidencialidad = evaluacion.clausula_confidencialidad
        $formEvaluacion.proyecto_id = evaluacion.proyecto_id
        $formEvaluacion.user_id = evaluacion.user_id
    }

    $: if ($formEvaluacion?.modificable) {
        $form.subsanacion = false
        $form.en_evaluacion = true
    } else {
        $form.subsanacion = proyecto.habilitado_para_evaluar == false && proyecto.modificable == true && proyecto.finalizado == false
    }

    $: if ($form?.subsanacion && $form?.en_evaluacion) {
        $form.en_evaluacion = false
    }
</script>

<AuthenticatedLayout>
    <header className="pt-[8rem]" slot="header">
        <div className="flex items-center justify-between lg:px-8 max-w-7xl mx-auto px-4 py-6 sm:px-6">
            <div>
                <h1 className="overflow-ellipsis overflow-hidden w-breadcrumb-ellipsis whitespace-nowrap flex items-center">
                    {#if isSuperAdmin || checkRole(authUser, [20, 18, 19, 5, 17])}
                        <a use:inertia href={route('proyectos.index')} className="text-app-400 hover:text-app-600"> Proyectos </a>
                    {/if}
                    <span className="text-app-400 font-medium mx-1.5">/</span>
                    {proyecto.codigo}
                    <a className="bg-app-600 text-white p-1 pr-5 rounded ml-2" href={route('convocatorias.proyectos.edit', [proyecto.convocatoria_id, proyecto.id])} target="_blank">
                        <span className="flex items-center">
                            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 mx-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
                            </svg>
                            <small> Ver detalles </small>
                        </span>
                    </a>
                </h1>
            </div>
        </div>
    </header>

    <div className="bg-white rounded shadow max-w-3xl">
        <form on:submit|preventDefault={submit}>
            <fieldset className="p-8">
                <div className="mt-8">
                    <Label labelFor="subsanacion" value="¿El proyecto puede ser subsanado? Nota: Si se selecciona la opción SI se finalizarán todas la evaluaciones del proyecto {proyecto.codigo}" className="inline-block mb-4" />
                    <br />
                    <Switch bind:checked={$form.subsanacion} />
                    <InputError message={errors.subsanacion} />

                    <InfoMessage className="mt-10">
                        <p className="font-black">Tenga en cuenta: Información del estado del proyecto (Se tienen en cuenta la(s) {proyecto?.evaluacionesHabilitadas} evaluacion(es) habilitada(s))</p>
                        <ul>
                            <li>Estado del proyecto: {JSON.parse(proyecto.estado)?.estado != '' ? JSON.parse(proyecto.estado)?.estado : proyecto.estado_cord_sennova ? JSON.parse(proyecto.estado_cord_sennova)?.estado : 'Sin estado'}</li>
                            <li>Número de recomendaciones: {JSON.parse(proyecto.estado)?.numeroRecomendaciones ? JSON.parse(proyecto.estado)?.numeroRecomendaciones : 0}</li>
                            {#if JSON.parse(proyecto.estado)?.puntaje}
                                <li>Puntaje total: {JSON.parse(proyecto.estado)?.puntaje ? JSON.parse(proyecto.estado)?.puntaje : 0}</li>
                            {/if}
                            <li>¿Requiere ser subsanado?: {JSON.parse(proyecto.estado)?.requiereSubsanar ? 'Si' : 'No'}</li>
                        </ul>
                    </InfoMessage>
                </div>

                <hr className="mt-10 mb-10" />

                <div className="mt-8">
                    <Label labelFor="en_evaluacion" value="¿El proyecto puede ser evaluado? Nota: Esta opción permite que los evaluadores visualicen el proyecto en su lista de evaluaciones" className="inline-block mb-4" />
                    <br />
                    <Switch bind:checked={$form.en_evaluacion} />
                    <InputError message={errors.en_evaluacion} />
                </div>

                <hr className="mt-10 mb-10" />

                <div className="mt-8">
                    <Label labelFor="radicado" value="¿El proyecto esta radicado? Nota: Si la opción es si evita que sea eliminado del sistema" className="inline-block mb-4" />
                    <br />
                    <Switch bind:checked={$form.radicado} />
                    <InputError message={errors.radicado} />
                </div>

                <hr className="mt-10 mb-10" />

                <div className="mt-8">
                    <Label labelFor="estado_cord_sennova" value="Por favor defina el estado del proyecto. (Solo si el proyecto tuvo uno revisión por la cord. SENNOVA)" className="inline-block mb-4" />
                    <br />
                    <Input label="Estado (Definido por la cord. SENNOVA)" id="estado_cord_sennova" type="text" className="mt-1" bind:value={$form.estado_cord_sennova} error={errors.estado_cord_sennova} />
                    <InputError message={errors.estado_cord_sennova} />
                </div>

                <hr className="mt-10 mb-10" />

                <div className="mt-8">
                    <Label labelFor="mostrar_recomendaciones" value="¿Los proponentes pueden observar las recomendaciones?" className="inline-block mb-4" />
                    <br />
                    <Switch bind:checked={$form.mostrar_recomendaciones} />
                    <InputError message={errors.mostrar_recomendaciones} />
                </div>

                <hr className="mt-10 mb-10" />

                <h1 className="p-4 font-black">Evaluadores</h1>

                {#each proyecto.evaluaciones as evaluacion}
                    <div className="flex items-center justify-between p-4 border border-t">
                        <p className="capitalize">{evaluacion.evaluador.nombre}</p>
                        <Button type="button" variant="raised" on:click={() => showEvaluacionDialog(evaluacion)}>Modificar</Button>
                    </div>
                {/each}
                {#if proyecto.evaluaciones.length == 0}
                    <p className="p-4">El proyecto no tiene evaluadores asignados</p>
                {/if}
            </fieldset>

            <div className="flex items-center justify-between mt-14 px-8 py-4">
                {#if isSuperAdmin || checkRole(authUser, [20, 18, 19, 5, 17])}
                    <PrimaryButton loading={$form.processing} className="ml-auto" type="submit">Guardar</PrimaryButton>
                {/if}
            </div>
        </form>
    </div>

    <Dialog bind:open={dialogOpen}>
        <div slot="title" className="flex items-center">Editar evaluación</div>
        <div slot="content">
            {#if showEvaluacionForm}
                <form on:submit|preventDefault={submitEvaluacion} id="evaluacion">
                    <fieldset className="p-8">
                        <div className="mt-8">
                            <Label className="mb-4" labelFor="user_id" value="Evaluador" />
                            <Select disabled={$formEvaluacion.clausula_confidencialidad} id="user_id" items={evaluadores} bind:selectedValue={$formEvaluacion.user_id} error={errors.user_id} autocomplete="off" placeholder="Seleccione un evaluador" required />
                            {#if $formEvaluacion.clausula_confidencialidad}
                                <InfoMessage alertMsg={true}>No se puede modificar el evaluador debido a que la evaluación ya tiene información registrada. Por favor genere una nueva evaluación con el nuevo evaluador y posteriormente deshabilite esta evaluación.</InfoMessage>
                            {/if}
                        </div>

                        <hr className="mt-10 mb-10" />

                        <div className="mt-8">
                            <Label labelFor="habilitado" value="¿La evaluación está habilitada? Nota: Una evaluación habilitada significa que el sistema la puede tomar para hacer el cálculo del promedio y asignar el estado del proyecto." className="inline-block mb-4" />
                            <br />
                            <Switch bind:checked={$formEvaluacion.habilitado} />
                            <InputError message={errors.habilitado} />
                        </div>

                        <hr className="mt-10 mb-10" />

                        <div className="mt-8">
                            <Label labelFor="modificable" value="¿La evaluación es modificable? Nota: Si la evaluación es modificable el evaluador podrá editar la información de la evaluación. Por otro lado el formulador NO podrá modicar la información del proyecto mientras se está realizando una evaluación." className="inline-block mb-4" />
                            <br />
                            <Switch bind:checked={$formEvaluacion.modificable} />
                            <InputError message={errors.modificable} />
                        </div>
                    </fieldset>
                </form>
            {/if}
        </div>
        <div slot="actions">
            <div className="p-4">
                <Button on:click={() => ((dialogOpen = false), ($form.subsanacion = proyecto.habilitado_para_evaluar == false && proyecto.modificable == true && proyecto.finalizado == false))} variant={null}>Cancelar</Button>

                <PrimaryButton loading={$formEvaluacion.processing} className="btn-gray ml-auto" type="submit" form="evaluacion">Guardar</PrimaryButton>
            </div>
        </div>
    </Dialog>
</AuthenticatedLayout>
